module.exports = [{ number: 2, english: "board", spanish: "tablero", ipa: "/bɔrd, boʊrd/" },
{ number: 1, english: "marvel", spanish: "maravilla", ipa: "/ˈmɑr vəl/" },
{ number: 3, english: "leash", spanish: "correa", ipa: "/liʃ/" },
{ number: 4, english: "electrical outlet", spanish: "toma corriente", ipa: "/ɪˈlɛk trɪ kəl ˈaʊt lɛt, -lɪt/" },
{ number: 5, english: "sunglasses", spanish: "gafas de sol", ipa: "/ˈsʌnˌglæs ɪz, -ˌglɑ sɪz/" },
{ number: 6, english: "screwdriver", spanish: "destornillador", ipa: "/ˈskruˌdraɪ vər/" },
{ number: 7, english: "tree", spanish: "árbol", ipa: "/tri/" },
{ number: 8, english: "astronaut", spanish: "astronauta", ipa: "/ˈæs trəˌnɔt, -ˌnɒt/" },
{ number: 9, english: "steam", spanish: "vapor", ipa: "/stim/" },
{ number: 10, english: "street", spanish: "calle", ipa: "/strit/" },
{ number: 11, english: "perfume", spanish: "perfume", ipa: "/ˈpɜr fyum/" },
{ number: 12, english: "soap", spanish: "jabón", ipa: "/soʊp/" },
{ number: 13, english: "blanket", spanish: "cobija", ipa: "/ˈblæŋ kɪt/" },
{ number: 14, english: "classroom", spanish: "salon de clase", ipa: "/ˈklæsˌrum/" },
{ number: 15, english: "lollipop", spanish: "chupeta", ipa: "/ˈlɒl iˌpɒp/" },
{ number: 16, english: "skunk", spanish: "mofeta, zorrillo", ipa: "/skʌŋk/" },
{ number: 17, english: "tablecloth", spanish: "mantel de mesa", ipa: "/ˈteɪ bəlˌklɔθ/" },
{ number: 18, english: "submarine", spanish: "submarino", ipa: "/'sʌb məˈrin/" },
{ number: 19, english: "handkerchief", spanish: "pañuelo", ipa: "/ˈhæŋ kər tʃɪf/" },
{ number: 20, english: "campfire", spanish: "hoguera, fogata", ipa: "/ˈkæmpˌfaɪər/" },
{ number: 21, english: "woodpecker", spanish: "pájaro carpintero", ipa: "/ˈwʊdˌpɛk ər/" },
{ number: 22, english: "sidewalk", spanish: "acera", ipa: "/ˈsaɪdˌwɔk/" },
{ number: 23, english: "crosswalk", spanish: "paso de peatones", ipa: "/ˈkrɔsˌwɔk, ˈkrɒs-/" },
{ number: 24, english: "flag", spanish: "bandera", ipa: "/flæg/" },
{ number: 25, english: "scepter", spanish: "cetro", ipa: "/ˈsɛp tər/" },
{ number: 26, english: "ear", spanish: "oreja", ipa: "/ɪər/" },
{ number: 27, english: "beret", spanish: "boina", ipa: "/bəˈreɪ/" },
{ number: 28, english: "column", spanish: "columna", ipa: "/ˈkɒl əm/" },
{ number: 29, english: "tool", spanish: "herramienta", ipa: "/tul/" },
{ number: 30, english: "fruit", spanish: "fruta", ipa: "/frut/" },
{ number: 31, english: "bus", spanish: "autobús", ipa: "/bʌs/" },
{ number: 32, english: "dictionary", spanish: "diccionario", ipa: "/ˈdɪk ʃəˌnɛr i/" },
{ number: 33, english: "pin", spanish: "alfiler", ipa: "/pɪn/" },
{ number: 34, english: "building", spanish: "edificio", ipa: "/ˈbɪl dɪŋ/" },
{ number: 35, english: "computer", spanish: "computadora", ipa: "/kəmˈpyu tər/" },
{ number: 36, english: "teacher", spanish: "profesor", ipa: "/ˈti tʃər/" },
{ number: 37, english: "week", spanish: "semana", ipa: "/wik/" },
{ number: 38, english: "cauldron", spanish: "caldero", ipa: "/ˈkɔl drən/" },
{ number: 39, english: "chameleon", spanish: "camaleón", ipa: "/kəˈmi li ən/" },
{ number: 40, english: "iceberg", spanish: "iceberg", ipa: "/ˈaɪs bɜrg/" },
{ number: 41, english: "kangaroo", spanish: "canguro", ipa: "/ˌkæŋ gəˈru/" },
{ number: 42, english: "snowman", spanish: "muñeco de nieve", ipa: "/ˈsnoʊˌmæn/" },
{ number: 43, english: "face", spanish: "cara", ipa: "/feɪs/" },
{ number: 44, english: "crayon", spanish: "crayon", ipa: "/ˈkreɪ ɒn, -ən/" },
{ number: 45, english: "peeler", spanish: "pelador", ipa: "/ˈpi lər/" },
{ number: 46, english: "mailman", spanish: "cartero", ipa: "/ˈmeɪlˌmæn/" },
{ number: 47, english: "boat", spanish: "bote", ipa: "/boʊt/" },
{ number: 48, english: "bat", spanish: "murciélago", ipa: "/bæt/" },
{ number: 49, english: "comb", spanish: "peine", ipa: "/koʊm/" },
{ number: 50, english: "island", spanish: "isla", ipa: "/ˈaɪ lənd/" },
{ number: 51, english: "city", spanish: "ciudad", ipa: "/ˈsɪt i/" },
{ number: 52, english: "backpack", spanish: "mochila", ipa: "/ˈbækˌpæk/" },
{ number: 54, english: "syringe", spanish: "jeringa, inyectadora", ipa: "/səˈrɪndʒ, ˈsɪr ɪndʒ/" },
{ number: 53, english: "lace", spanish: "encaje", ipa: "/leɪs/" },
{ number: 55, english: "candlestick", spanish: "candelero", ipa: "/ˈkæn dlˌstɪk/" },
{ number: 56, english: "crate", spanish: "caja (madera almacenaje)", ipa: "/kreɪt/" },
{ number: 57, english: "cattle", spanish: "ganado vacuno", ipa: "/ˈkæt l/" },
{ number: 58, english: "bookstore", spanish: "librería", ipa: "/ˈbʊkˌstɔr, -ˌstoʊr/" },
{ number: 59, english: "hood", spanish: "capucha", ipa: "/hʊd/" },
{ number: 60, english: "cord", spanish: "cuerda", ipa: "/kɔrd/" },
{ number: 61, english: "cherry", spanish: "cereza", ipa: "/ˈtʃɛr i/" },
{ number: 62, english: "ribbon", spanish: "cinta, lazo", ipa: "/ˈrɪb ən/" },
{ number: 63, english: "bear", spanish: "oso", ipa: "/bɛər/" },
{ number: 64, english: "bandage", spanish: "vendaje", ipa: "/ˈbæn dɪdʒ/" },
{ number: 65, english: "battery", spanish: "batería", ipa: "/ˈbæt ə ri/" },
{ number: 66, english: "worm", spanish: "gusano", ipa: "/wɜrm/" },
{ number: 67, english: "carpenter", spanish: "carpintero", ipa: "/ˈkɑr pən tər/" },
{ number: 68, english: "park", spanish: "parque", ipa: "/pɑrk/" },
{ number: 69, english: "garbage", spanish: "basura", ipa: "/ˈgɑr bɪdʒ/" },
{ number: 70, english: "racket", spanish: "raqueta", ipa: "/ˈræk ɪt/" },
{ number: 71, english: "excavator", spanish: "excavador", ipa: "/ˈɛks kəˌveɪ tər/" },
{ number: 72, english: "armor", spanish: "armadura", ipa: "/ˈɑr mər/" },
{ number: 73, english: "angel", spanish: "ángel", ipa: "/ˈeɪn dʒəl/" },
{ number: 74, english: "seahorse", spanish: "caballo de mar", ipa: "/'si hɔrs/" },
{ number: 75, english: "card", spanish: "tarjeta", ipa: "/kɑrd/" },
{ number: 76, english: "smile", spanish: "sonrisa", ipa: "/smaɪl/" },
{ number: 77, english: "stomach", spanish: "estómago", ipa: "/ˈstʌm ək/" },
{ number: 78, english: "coat", spanish: "abrigo", ipa: "/koʊt/" },
{ number: 79, english: "cactus", spanish: "cactus", ipa: "/ˈkæk təs/" },
{ number: 80, english: "patch", spanish: "parche", ipa: "/pætʃ/" },
{ number: 81, english: "bucket", spanish: "tobo", ipa: "/ˈbʌk ɪt/" },
{ number: 82, english: "rose", spanish: "rosa", ipa: "/roʊz/" },
{ number: 83, english: "clothespin", spanish: "pinza de la ropa", ipa: "/ˈkloʊzˌpɪn/" },
{ number: 84, english: "medal", spanish: "medalla", ipa: "/ˈmɛd l/" },
{ number: 85, english: "orchard", spanish: "huerta", ipa: "/ˈɔr tʃərd/" },
{ number: 86, english: "camera", spanish: "cámara", ipa: "/ˈkæm ər ə, ˈkæm rə/" },
{ number: 87, english: "arm", spanish: "brazo", ipa: "/ɑrm/" },
{ number: 88, english: "mermaid", spanish: "sirena", ipa: "/ˈmɜrˌmeɪd/" },
{ number: 89, english: "engine", spanish: "motor", ipa: "/ˈɛn dʒən/" },
{ number: 90, english: "bench", spanish: "banco (sentarse)", ipa: "/bɛntʃ/" },
{ number: 91, english: "glasses", spanish: "gafas", ipa: "/glæs, glɑs/" },
{ number: 92, english: "oven", spanish: "horno", ipa: "/ˈʌv ən/" },
{ number: 93, english: "spider", spanish: "araña", ipa: "/ˈspaɪ dər/" },
{ number: 94, english: "earring", spanish: "zarcillo", ipa: "/ˈɪərˌrɪŋ, -ɪŋ/" },
{ number: 95, english: "whistle", spanish: "silbato", ipa: "/ˈʰwɪs əl, ˈwɪs-/" },
{ number: 96, english: "pajama", spanish: "pijama", ipa: "/pəˈdʒɑ mə, -ˈdʒæm ə/" },
{ number: 97, english: "eagle", spanish: "águila", ipa: "/ˈi gəl/" },
{ number: 98, english: "lobster", spanish: "langosta", ipa: "/ˈlɒb stər/" },
{ number: 99, english: "lemon", spanish: "limón", ipa: "/ˈlɛm ən/" },
{ number: 100, english: "shadow", spanish: "sombra", ipa: "/ˈʃæd oʊ/" },
{ number: 101, english: "pincers", spanish: "tenazas", ipa: "/ˈpɪn sərz/" },
{ number: 102, english: "church", spanish: "iglesia", ipa: "/tʃɜrtʃ/" },
{ number: 103, english: "eye", spanish: "ojo", ipa: "/aɪ/" },
{ number: 104, english: "attic", spanish: "ático", ipa: "/ˈæt ɪk/" },
{ number: 105, english: "storm", spanish: "tormenta", ipa: "/stɔrm/" },
{ number: 107, english: "vacuum", spanish: "aspiradora", ipa: "/ˈvæk yum, -yu əm/" },
{ number: 109, english: "cabbage", spanish: "repollo", ipa: "/ˈkæb ɪdʒ/" },
{ number: 108, english: "lifeguard", spanish: "salvavidas", ipa: "/ˈlaɪfˌgɑrd/" },
{ number: 110, english: "strawberry", spanish: "fresa", ipa: "/ˈstrɔˌbɛr i, -bə ri/" },
{ number: 112, english: "puddle", spanish: "charco", ipa: "/ˈpʌd l/" },
{ number: 111, english: "locker", spanish: "armario", ipa: "/ˈlɒk ər/" },
{ number: 113, english: "groom", spanish: "novio (boda)", ipa: "/grum, grʊm/" },
{ number: 115, english: "rabbit", spanish: "conejo", ipa: "/ˈræb ɪt/" },
{ number: 116, english: "snow", spanish: "nieve", ipa: "/snoʊ/" },
{ number: 117, english: "hazelnut", spanish: "avellana", ipa: "/ˈheɪ zəlˌnʌt/" },
{ number: 119, english: "fan", spanish: "ventilador", ipa: "/fæn/" },
{ number: 114, english: "raspberry", spanish: "frambuesa", ipa: "/ˈræzˌbɛr i/" },
{ number: 118, english: "crane", spanish: "grúa", ipa: "/kreɪn/" },
{ number: 121, english: "hair", spanish: "cabello", ipa: "/hɛər/" },
{ number: 122, english: "donkey", spanish: "burro", ipa: "/ˈdɒŋ ki, ˈdɔŋ-, ˈdʌŋ-/" },
{ number: 124, english: "calf", spanish: "becerro", ipa: "/kæf, kɑf/" },
{ number: 120, english: "armchair", spanish: "sillón", ipa: "/ˈɑrmˌtʃɛər/" },
{ number: 125, english: "umbrella", spanish: "paraguas", ipa: "/ʌmˈbrɛl ə/" },
{ number: 127, english: "grandfather", spanish: "abuelo", ipa: "/ˈgrænˌfɑ ðər, ˈgrænd-/" },
{ number: 128, english: "wedding", spanish: "boda", ipa: "/ˈwɛd ɪŋ/" },
{ number: 126, english: "eyebrow", spanish: "ceja", ipa: "/ˈaɪˌbraʊ/" },
{ number: 129, english: "sailor", spanish: "marinero", ipa: "/ˈseɪ lər/" },
{ number: 130, english: "skateboard", spanish: "patineta", ipa: "/ˈskeɪtˌbɔrd, -ˌboʊrd/" },
{ number: 132, english: "river", spanish: "río", ipa: "/ˈrɪv ər/" },
{ number: 133, english: "dandelion", spanish: "diente de león", ipa: "/ˈdæn dlˌaɪ ən/" },
{ number: 134, english: "pencil", spanish: "lápiz", ipa: "/ˈpɛn səl/" },
{ number: 135, english: "funnel", spanish: "embudo", ipa: "/ˈfʌn l/" },
{ number: 136, english: "drain", spanish: "desagüe", ipa: "/dreɪn/" },
{ number: 137, english: "painter", spanish: "pintor", ipa: "/ˈpeɪn tər/" },
{ number: 138, english: "cow", spanish: "vaca", ipa: "/kaʊ/" },
{ number: 123, english: "hat", spanish: "sombrero", ipa: "/hæt/" },
{ number: 139, english: "chili pepper", spanish: "ají picante", ipa: "/ˈtʃɪl i ˈpɛp ər/" },
{ number: 131, english: "beard", spanish: "barba", ipa: "/bɪərd/" },
{ number: 140, english: "lighthouse", spanish: "faro", ipa: "/ˈlaɪtˌhaʊs/" },
{ number: 142, english: "thermometer", spanish: "termómetro", ipa: "/θərˈmɒm ɪ tər/" },
{ number: 143, english: "paddle", spanish: "paleta", ipa: "/ˈpæd l/" },
{ number: 144, english: "man", spanish: "hombre", ipa: "/mæn/" },
{ number: 145, english: "helmet", spanish: "casco", ipa: "/ˈhɛl mɪt/" },
{ number: 146, english: "forehead", spanish: "frente", ipa: "/ˈfɔr ɪd/" },
{ number: 147, english: "hospital", spanish: "hospital", ipa: "/ˈhɒs pɪ tl/" },
{ number: 149, english: "acorn", spanish: "bellota", ipa: "/ˈeɪ kɔrn, ˈeɪ kərn/" },
{ number: 150, english: "beggar", spanish: "mendigo", ipa: "/ˈbɛg ər/" },
{ number: 148, english: "gutter", spanish: "canal (agua)", ipa: "/ˈgʌt ər/" },
{ number: 152, english: "well", spanish: "pozo", ipa: "/wɛl/" },
{ number: 106, english: "boy", spanish: "chico", ipa: "/bɔɪ/" },
{ number: 153, english: "palace", spanish: "palacio", ipa: "/ˈpæl ɪs/" },
{ number: 151, english: "apron", spanish: "delantal", ipa: "/ˈeɪ prən/" },
{ number: 154, english: "chopsticks", spanish: "palillos", ipa: "/ˈtʃɒpˌstɪks/" },
{ number: 156, english: "diamond", spanish: "diamante", ipa: "/ˈdaɪ mənd, ˈdaɪ ə-/" },
{ number: 158, english: "rat", spanish: "rata", ipa: "/ræt/" },
{ number: 141, english: "thread", spanish: "hilo", ipa: "/θrɛd/" },
{ number: 159, english: "wallet", spanish: "billetera", ipa: "/ˈwɒl ɪt, ˈwɔ lɪt/" },
{ number: 157, english: "pony", spanish: "poni", ipa: "/ˈpoʊ ni/" },
{ number: 161, english: "vase", spanish: "florero", ipa: "/veɪs, veɪz, vɑz/" },
{ number: 160, english: "safe", spanish: "caja fuerte", ipa: "/seɪf/" },
{ number: 163, english: "policeman", spanish: "policía", ipa: "/pəˈlis mən/" },
{ number: 164, english: "helicopter", spanish: "helicóptero", ipa: "/ˈhɛl ɪˌkɒp tər, ˈhi lɪ-/" },
{ number: 155, english: "lawn", spanish: "césped", ipa: "/lɔn/" },
{ number: 162, english: "fork", spanish: "tenedor", ipa: "/fɔrk/" },
{ number: 166, english: "carriage", spanish: "carruaje", ipa: "/ˈkær ɪdʒ/" },
{ number: 167, english: "butcher shop", spanish: "carnicería", ipa: "/ˈbʊtʃ ər ʃɒp/" },
{ number: 170, english: "dishwasher", spanish: "lavavajillas", ipa: "/ˈdɪʃˌwɒʃ ər, -ˌwɔ ʃər/" },
{ number: 171, english: "scissors", spanish: "tijeras", ipa: "/ˈsɪz ərz/" },
{ number: 168, english: "mattress", spanish: "colchón", ipa: "/ˈmæ trɪs/" },
{ number: 169, english: "frame", spanish: "marco", ipa: "/freɪm/" },
{ number: 165, english: "runner", spanish: "corredor", ipa: "/ˈrʌn ər/" },
{ number: 174, english: "corkscrew", spanish: "sacacorchos", ipa: "/ˈkɔrkˌskru/" },
{ number: 172, english: "sofa", spanish: "sofá", ipa: "/ˈsoʊ fə/" },
{ number: 173, english: "ceiling", spanish: "techo", ipa: "/ˈsi lɪŋ/" },
{ number: 177, english: "sail", spanish: "velero (barco)", ipa: "/seɪl/" },
{ number: 175, english: "carpet", spanish: "alfombra", ipa: "/ˈkɑr pɪt/" },
{ number: 178, english: "lizard", spanish: "lagartija", ipa: "/ˈlɪz ərd/" },
{ number: 180, english: "projector", spanish: "proyector", ipa: "/prəˈdʒɛk tər/" },
{ number: 182, english: "sea", spanish: "mar", ipa: "/si/" },
{ number: 176, english: "pipe", spanish: "tubo", ipa: "/paɪp/" },
{ number: 183, english: "skirt", spanish: "falda", ipa: "/skɜrt/" },
{ number: 181, english: "archer", spanish: "arquero", ipa: "/ˈɑr tʃər/" },
{ number: 185, english: "foot", spanish: "pie", ipa: "/fʊt/" },
{ number: 186, english: "hammer", spanish: "martillo", ipa: "/ˈhæm ər/" },
{ number: 187, english: "puppy", spanish: "perrito", ipa: "/ˈpʌp i/" },
{ number: 188, english: "spade", spanish: "pala", ipa: "/speɪd/" },
{ number: 179, english: "swing", spanish: "columpio", ipa: "/swɪŋ/" },
{ number: 190, english: "drought", spanish: "sequía", ipa: "/draʊt/" },
{ number: 189, english: "grater", spanish: "rallador", ipa: "/ˈgreɪ tər/" },
{ number: 191, english: "cellar", spanish: "bodega (almacenaje)", ipa: "/ˈsɛl ər/" },
{ number: 192, english: "watermelon", spanish: "sandía", ipa: "/ˈwɔ tərˌmɛl ən/" },
{ number: 195, english: "swimsuit", spanish: "traje de baño", ipa: "/ˈswɪmˌsut/" },
{ number: 196, english: "mug", spanish: "taza grande", ipa: "/mʌg/" },
{ number: 184, english: "priest", spanish: "sacerdote", ipa: "/prist/" },
{ number: 197, english: "parsley", spanish: "perejil", ipa: "/ˈpɑr sli/" },
{ number: 193, english: "singer", spanish: "cantante", ipa: "/ˈsɪŋ ər/" },
{ number: 199, english: "sink", spanish: "fregadero", ipa: "/sɪŋk/" },
{ number: 200, english: "witch", spanish: "bruja", ipa: "/wɪtʃ/" },
{ number: 201, english: "mushroom", spanish: "seta, hongo", ipa: "/ˈmʌʃ rum, -rʊm/" },
{ number: 202, english: "mountain", spanish: "montaña", ipa: "/ˈmaʊn tn/" },
{ number: 203, english: "nutcracker", spanish: "cascanueces", ipa: "/ˈnʌtˌkræk ər/" },
{ number: 204, english: "drill", spanish: "taladro", ipa: "/drɪl/" },
{ number: 205, english: "seesaw", spanish: "subibaja", ipa: "/ˈsiˌsɔ/" },
{ number: 206, english: "blacksmith", spanish: "herrero", ipa: "/ˈblækˌsmɪθ/" },
{ number: 207, english: "hedgehog", spanish: "erizo", ipa: "/ˈhɛdʒˌhɒg, -ˌhɔg/" },
{ number: 208, english: "crab", spanish: "cangrejo", ipa: "/kræb/" },
{ number: 209, english: "beet", spanish: "remolacha", ipa: "/bit/" },
{ number: 210, english: "seaweed", spanish: "algas marinas", ipa: "/ˈsiˌwid/" },
{ number: 211, english: "slide", spanish: "diapositiva", ipa: "/slaɪd/" },
{ number: 212, english: "shield", spanish: "escudo", ipa: "/ʃild/" },
{ number: 213, english: "jacket", spanish: "chaqueta", ipa: "/ˈdʒæk ɪt/" },
{ number: 214, english: "pirate", spanish: "pirata", ipa: "/ˈpaɪ rət/" },
{ number: 215, english: "suspenders", spanish: "tirantes", ipa: "/səˈspɛn dər/" },
{ number: 216, english: "spine", spanish: "espina", ipa: "/spaɪn/" },
{ number: 217, english: "tie", spanish: "corbata", ipa: "/taɪ/" },
{ number: 194, english: "earth", spanish: "tierra", ipa: "/ɜrθ/" },
{ number: 218, english: "dark", spanish: "oscuridad", ipa: "/dɑrk/" },
{ number: 220, english: "sleeping bag", spanish: "bolsa de dormir", ipa: "/ˈsli pɪŋ bæg/" },
{ number: 219, english: "plait", spanish: "trenza", ipa: "/pleɪt, plæt/" },
{ number: 221, english: "vegetable", spanish: "vegetal", ipa: "/ˈvɛdʒ tə bəl/" },
{ number: 222, english: "thumbtack", spanish: "chinche", ipa: "/ˈθʌmˌtæk/" },
{ number: 224, english: "volcano", spanish: "volcán", ipa: "/vɒlˈkeɪ noʊ/" },
{ number: 223, english: "binoculars", spanish: "prismáticos", ipa: "/bəˈnɒk yə lər, baɪ-/" },
{ number: 225, english: "nurse", spanish: "enfermera", ipa: "/nɜrs/" },
{ number: 227, english: "water", spanish: "agua", ipa: "/ˈwɔ tər, ˈwɒt ər/" },
{ number: 228, english: "dwarf", spanish: "enano", ipa: "/dwɔrf/" },
{ number: 229, english: "zipper", spanish: "cremallera", ipa: "/ˈzɪp ər/" },
{ number: 230, english: "sleet", spanish: "aguanieve", ipa: "/slit/" },
{ number: 231, english: "buttocks", spanish: "nalgas", ipa: "/ˈbʌt ək/" },
{ number: 232, english: "book", spanish: "libro", ipa: "/bʊk/" },
{ number: 198, english: "juice", spanish: "jugo", ipa: "/dʒus/" },
{ number: 233, english: "paper", spanish: "papel", ipa: "/ˈpeɪ pər/" },
{ number: 235, english: "werewolf", spanish: "hombre-lobo", ipa: "/ˈwɛərˌwʊlf/" },
{ number: 236, english: "pocket", spanish: "bolsillo", ipa: "/ˈpɒk ɪt/" },
{ number: 237, english: "kite", spanish: "cometa (juguete)", ipa: "/kaɪt/" },
{ number: 238, english: "toothbrush", spanish: "cepillo de dientes", ipa: "/ˈtuθˌbrʌʃ/" },
{ number: 240, english: "poo", spanish: "pupú", ipa: "/pu/" },
{ number: 239, english: "sheep", spanish: "oveja", ipa: "/ʃip/" },
{ number: 241, english: "stork", spanish: "cigüeña", ipa: "/stɔrk/" },
{ number: 243, english: "log", spanish: "madero", ipa: "/lɔg, lɒg/" },
{ number: 244, english: "airplane", spanish: "avión", ipa: "/ˈɛərˌpleɪn/" },
{ number: 245, english: "spring", spanish: "primavera", ipa: "/sprɪŋ/" },
{ number: 246, english: "bathrobe", spanish: "bata de baño", ipa: "/ˈbæθˌroʊb, ˈbɑθ-/" },
{ number: 247, english: "turkey", spanish: "pavo", ipa: "/ˈtɜr ki/" },
{ number: 248, english: "tennis", spanish: "tenis", ipa: "/ˈtɛn ɪs/" },
{ number: 242, english: "tea", spanish: "té", ipa: "/ti/" },
{ number: 234, english: "cave", spanish: "cueva", ipa: "/keɪv/" },
{ number: 250, english: "windmill", spanish: "molino", ipa: "/ˈwɪndˌmɪl/" },
{ number: 251, english: "ladybug", spanish: "mariquita", ipa: "/ˈleɪ diˌbʌg/" },
{ number: 226, english: "gate", spanish: "portón", ipa: "/geɪt/" },
{ number: 249, english: "feather", spanish: "pluma", ipa: "/ˈfɛð ər/" },
{ number: 254, english: "referee", spanish: "árbitro", ipa: "/ˌrɛf əˈri/" },
{ number: 253, english: "trunk", spanish: "maletero, baúl", ipa: "/trʌŋk/" },
{ number: 255, english: "crown", spanish: "corona", ipa: "/kraʊn/" },
{ number: 257, english: "bathtub", spanish: "bañera", ipa: "/ˈbæθˌtʌb, ˈbɑθ-/" },
{ number: 256, english: "jewelry", spanish: "joyería", ipa: "/ˈdʒu əl ri/" },
{ number: 258, english: "walrus", spanish: "morsa", ipa: "/ˈwɔl rəs, ˈwɒl-/" },
{ number: 261, english: "windowsill", spanish: "antepecho (ventana)", ipa: "/ˈwɪn doʊˌsɪl/" },
{ number: 262, english: "plunger", spanish: "destapa caño", ipa: "/ˈplʌn dʒər/" },
{ number: 263, english: "steering wheel", spanish: "volante", ipa: "/ˈstɪər ɪŋ ʰwil, wil/" },
{ number: 264, english: "shirt", spanish: "camisa", ipa: "/ʃɜrt/" },
{ number: 265, english: "anteater", spanish: "oso hormiguero", ipa: "/ˈæntˌi tər/" },
{ number: 266, english: "cube", spanish: "cubo", ipa: "/kyub/" },
{ number: 259, english: "hen", spanish: "gallina", ipa: "/hɛn/" },
{ number: 260, english: "globe", spanish: "globo", ipa: "/gloʊb/" },
{ number: 268, english: "blackboard", spanish: "pizarra", ipa: "/ˈblækˌbɔrd, -ˌboʊrd/" },
{ number: 270, english: "tunnel", spanish: "túnel", ipa: "/ˈtʌn l/" },
{ number: 269, english: "pilot", spanish: "piloto", ipa: "/ˈpaɪ lət/" },
{ number: 272, english: "cleats", spanish: "tacos (zapatos)", ipa: "/klit/" },
{ number: 273, english: "thimble", spanish: "dedal", ipa: "/ˈθɪm bəl/" },
{ number: 274, english: "cobweb", spanish: "telaraña", ipa: "/ˈkɒbˌwɛb/" },
{ number: 275, english: "grandmother", spanish: "abuela", ipa: "/ˈgrænˌmʌð ər/" },
{ number: 276, english: "snail", spanish: "caracol", ipa: "/sneɪl/" },
{ number: 277, english: "bedroom", spanish: "cuarto", ipa: "/ˈbɛdˌrum, -ˌrʊm/" },
{ number: 278, english: "lamb", spanish: "cordero", ipa: "/læm/" },
{ number: 252, english: "fire", spanish: "fuego", ipa: "/faɪər/" },
{ number: 279, english: "brain", spanish: "cerebro", ipa: "/breɪn/" },
{ number: 267, english: "nut", spanish: "nuez", ipa: "/nʌt/" },
{ number: 281, english: "handcuffs", spanish: "esposas", ipa: "/ˈhændˌkʌf/" },
{ number: 284, english: "petal", spanish: "pétalo", ipa: "/ˈpɛt l/" },
{ number: 285, english: "princess", spanish: "princesa", ipa: "/ˈprɪn sɪs, -sɛs, prɪnˈsɛs/" },
{ number: 286, english: "coconut", spanish: "coco", ipa: "/ˈkoʊ kəˌnʌt, -nət/" },
{ number: 287, english: "fall", spanish: "otoño", ipa: "/fɔl/" },
{ number: 283, english: "tattoo", spanish: "tatuaje", ipa: "/tæˈtu/" },
{ number: 289, english: "bulb", spanish: "bombilla", ipa: "/bʌlb/" },
{ number: 290, english: "goose", spanish: "ganso", ipa: "/gus/" },
{ number: 288, english: "lack", spanish: "ausencia", ipa: "/læk/" },
{ number: 291, english: "jester", spanish: "bufón", ipa: "/ˈdʒɛs tər/" },
{ number: 292, english: "bun", spanish: "bollo", ipa: "/bʌn/" },
{ number: 280, english: "claw", spanish: "garra", ipa: "/klɔ/" },
{ number: 293, english: "slave", spanish: "esclavo", ipa: "/sleɪv/" },
{ number: 296, english: "chimney", spanish: "chimenea", ipa: "/ˈtʃɪm ni/" },
{ number: 297, english: "maize", spanish: "maíz", ipa: "/meɪz/" },
{ number: 295, english: "stool", spanish: "taburete", ipa: "/stul/" },
{ number: 299, english: "cupboard", spanish: "alacena", ipa: "/ˈkʌb ərd/" },
{ number: 300, english: "knot", spanish: "nudo", ipa: "/nɒt/" },
{ number: 294, english: "heel", spanish: "tacón", ipa: "/hil/" },
{ number: 301, english: "broom", spanish: "escoba", ipa: "/brum, brʊm/" },
{ number: 302, english: "stapler", spanish: "engrapadora", ipa: "/ˈsteɪ plər/" },
{ number: 298, english: "veil", spanish: "velo", ipa: "/veɪl/" },
{ number: 271, english: "arch", spanish: "arco", ipa: "/ɑrtʃ/" },
{ number: 305, english: "strainer", spanish: "colador", ipa: "/ˈstreɪ nər/" },
{ number: 304, english: "dustpan", spanish: "recogedor", ipa: "/ˈdʌstˌpæn/" },
{ number: 306, english: "caterpillar", spanish: "oruga", ipa: "/ˈkæt əˌpɪl ər, ˈkæt ər-/" },
{ number: 307, english: "jug", spanish: "jarra", ipa: "/dʒʌg/" },
{ number: 309, english: "thumb", spanish: "pulgar", ipa: "/θʌm/" },
{ number: 310, english: "receipt", spanish: "recibo", ipa: "/rɪˈsit/" },
{ number: 311, english: "cheek", spanish: "mejilla", ipa: "/tʃik/" },
{ number: 312, english: "flour", spanish: "harina", ipa: "/flaʊər, ˈflaʊ ər/" },
{ number: 314, english: "chest", spanish: "pecho", ipa: "/tʃɛst/" },
{ number: 303, english: "rake", spanish: "rastrillo", ipa: "/reɪk/" },
{ number: 313, english: "whale", spanish: "ballena", ipa: "/ʰweɪl, weɪl/" },
{ number: 316, english: "envelope", spanish: "sobre (carta), envoltura", ipa: "/ˈɛn vəˌloʊp, ˈɑn-/" },
{ number: 318, english: "sausage", spanish: "salchicha", ipa: "/ˈsɔ sɪdʒ/" },
{ number: 319, english: "garlic", spanish: "ajo", ipa: "/ˈgɑr lɪk/" },
{ number: 320, english: "sock", spanish: "calcetín", ipa: "/sɒk/" },
{ number: 317, english: "blind", spanish: "persiana", ipa: "/blaɪnd/" },
{ number: 322, english: "tray", spanish: "bandeja", ipa: "/treɪ/" },
{ number: 321, english: "balloon", spanish: "globo", ipa: "/bəˈlun/" },
{ number: 324, english: "ostrich", spanish: "avestruz", ipa: "/ˈɔ strɪtʃ, ˈɒs trɪtʃ/" },
{ number: 325, english: "jigsaw", spanish: "rompecabezas", ipa: "/ˈdʒɪgˌsɔ/" },
{ number: 326, english: "fist", spanish: "puño", ipa: "/fɪst/" },
{ number: 327, english: "wasp", spanish: "avispa", ipa: "/wɒsp/" },
{ number: 328, english: "peacock", spanish: "pavo real", ipa: "/ˈpiˌkɒk/" },
{ number: 329, english: "brick", spanish: "ladrillo", ipa: "/brɪk/" },
{ number: 330, english: "throat", spanish: "garganta", ipa: "/θroʊt/" },
{ number: 331, english: "fridge", spanish: "refrigerador", ipa: "/frɪdʒ/" },
{ number: 332, english: "spanner", spanish: "llave inglesa", ipa: "/ˈspæn ər/" },
{ number: 333, english: "stretcher", spanish: "camilla", ipa: "/ˈstrɛtʃ ər/" },
{ number: 334, english: "flood", spanish: "inundación", ipa: "/flʌd/" },
{ number: 335, english: "puppet", spanish: "marioneta", ipa: "/ˈpʌp ɪt/" },
{ number: 336, english: "blouse", spanish: "blusa", ipa: "/blaʊs, blaʊz/" },
{ number: 337, english: "fin", spanish: "aleta", ipa: "/fɪn/" },
{ number: 323, english: "grape", spanish: "uva", ipa: "/greɪp/" },
{ number: 338, english: "needle", spanish: "aguja", ipa: "/ˈnid l/" },
{ number: 340, english: "thigh", spanish: "muslo", ipa: "/θaɪ/" },
{ number: 341, english: "mud", spanish: "barro", ipa: "/mʌd/" },
{ number: 339, english: "pot", spanish: "maceta", ipa: "/pɒt/" },
{ number: 342, english: "escalator", spanish: "escalera mecánica", ipa: "/ˈɛs kəˌleɪ tər/" },
{ number: 344, english: "parrot", spanish: "loro", ipa: "/ˈpær ət/" },
{ number: 345, english: "tire", spanish: "neumático", ipa: "/taɪər/" },
{ number: 346, english: "avocado", spanish: "aguacate", ipa: "/ˌæv əˈkɑ doʊ, ˌɑ və-/" },
{ number: 347, english: "keyhole", spanish: "ojo de cerradura", ipa: "/ˈkiˌhoʊl/" },
{ number: 348, english: "carrot", spanish: "zanahoria", ipa: "/ˈkær ət/" },
{ number: 349, english: "beetroot", spanish: "remolacha", ipa: "/ˈbitˌrut, -ˌrʊt/" },
{ number: 350, english: "gear", spanish: "engranaje", ipa: "/gɪər/" },
{ number: 351, english: "lung", spanish: "pulmón", ipa: "/lʌŋ/" },
{ number: 352, english: "squirrel", spanish: "ardilla", ipa: "/ˈskwɜr əl/" },
{ number: 353, english: "drop", spanish: "gota", ipa: "/drɒp/" },
{ number: 343, english: "trap", spanish: "trampa", ipa: "/træp/" },
{ number: 354, english: "roller", spanish: "rodillo", ipa: "/ˈroʊ lər/" },
{ number: 356, english: "pear", spanish: "pera", ipa: "/pɛər/" },
{ number: 357, english: "mole", spanish: "topo", ipa: "/moʊl/" },
{ number: 358, english: "beak", spanish: "pico (animal)", ipa: "/bik/" },
{ number: 359, english: "pumpkin", spanish: "calabaza", ipa: "/ˈpʌmp kɪn/" },
{ number: 360, english: "screw", spanish: "tornillo", ipa: "/skru/" },
{ number: 361, english: "wagon", spanish: "vagón", ipa: "/ˈwæg ən/" },
{ number: 362, english: "cutlery", spanish: "cuchillería", ipa: "/ˈkʌt lə ri/" },
{ number: 363, english: "nun", spanish: "monja", ipa: "/nʌn/" },
{ number: 308, english: "wig", spanish: "peluca", ipa: "/wɪg/" },
{ number: 364, english: "owl", spanish: "búho", ipa: "/aʊl/" },
{ number: 365, english: "snowflake", spanish: "copo de nieve", ipa: "/ˈsnoʊˌfleɪk/" },
{ number: 366, english: "wire", spanish: "cable", ipa: "/waɪər/" },
{ number: 367, english: "tailor", spanish: "sastre", ipa: "/ˈteɪ lər/" },
{ number: 368, english: "belly", spanish: "vientre, panza", ipa: "/ˈbɛl i/" },
{ number: 369, english: "uniform", spanish: "uniforme", ipa: "/ˈyu nəˌfɔrm/" },
{ number: 370, english: "neck", spanish: "cuello", ipa: "/nɛk/" },
{ number: 371, english: "slipper", spanish: "zapatilla, pantufla", ipa: "/ˈslɪp ər/" },
{ number: 372, english: "suit", spanish: "traje", ipa: "/sut/" },
{ number: 373, english: "knife", spanish: "cuchillo", ipa: "/naɪf/" },
{ number: 374, english: "shower", spanish: "ducha", ipa: "/ˈʃaʊ ər/" },
{ number: 375, english: "fire extinguisher", spanish: "extintor de incendios", ipa: "/faɪər ɪkˈstɪŋ gwɪ ʃər/" },
{ number: 376, english: "kettle", spanish: "tetera", ipa: "/ˈkɛt l/" },
{ number: 377, english: "can", spanish: "lata", ipa: "/kæn/" },
{ number: 378, english: "arrow", spanish: "flecha", ipa: "/ˈær oʊ/" },
{ number: 379, english: "rectangle", spanish: "rectángulo", ipa: "/ˈrɛkˌtæŋ gəl/" },
{ number: 380, english: "rope", spanish: "cuerda", ipa: "/roʊp/" },
{ number: 381, english: "calculator", spanish: "calculadora", ipa: "/ˈkæl kyəˌleɪ tər/" },
{ number: 382, english: "iron", spanish: "hierro, plancha", ipa: "/ˈaɪ ərn/" },
{ number: 383, english: "ruler", spanish: "regla", ipa: "/ˈru lər/" },
{ number: 384, english: "accordion", spanish: "acordeón", ipa: "/əˈkɔr di ən/" },
{ number: 385, english: "closet", spanish: "armario", ipa: "/ˈklɒz ɪt/" },
{ number: 386, english: "spear", spanish: "lanza", ipa: "/spɪər/" },
{ number: 387, english: "satellite", spanish: "satélite", ipa: "/ˈsæt lˌaɪt/" },
{ number: 388, english: "treasure", spanish: "tesoro", ipa: "/ˈtrɛʒ ər/" },
{ number: 389, english: "pencil sharpener", spanish: "sacapuntas", ipa: "/ˈpɛn səl ˈʃɑr pən/" },
{ number: 390, english: "typewriter", spanish: "máquina de escribir", ipa: "/ˈtaɪpˌraɪ tər/" },
{ number: 391, english: "circle", spanish: "círculo", ipa: "/ˈsɜr kəl/" },
{ number: 392, english: "pickaxe", spanish: "pico (herramienta)", ipa: "/ˈpɪkˌæks/" },
{ number: 393, english: "hammock", spanish: "hamaca", ipa: "/ˈhæm ək/" },
{ number: 315, english: "cap", spanish: "gorra", ipa: "/kæp/" },
{ number: 355, english: "wing", spanish: "ala", ipa: "/wɪŋ/" },
{ number: 394, english: "whip", spanish: "látigo", ipa: "/ʰwɪp, wɪp/" },
{ number: 395, english: "anchor", spanish: "ancla", ipa: "/ˈæŋ kər/" },
{ number: 396, english: "letter", spanish: "carta", ipa: "/ˈlɛt ər/" },
{ number: 397, english: "curtain", spanish: "cortina", ipa: "/ˈkɜr tn/" },
{ number: 398, english: "refrigerator", spanish: "refrigerador", ipa: "/rɪˈfrɪdʒ əˌreɪ tər/" },
{ number: 399, english: "door", spanish: "puerta", ipa: "/dɔr, doʊr/" },
{ number: 400, english: "flashlight", spanish: "linterna", ipa: "/ˈflæʃˌlaɪt/" },
{ number: 401, english: "doll", spanish: "muñeca", ipa: "/dɒl/" },
{ number: 402, english: "walking stick", spanish: "bastón", ipa: "/ˈwɔ kɪŋ stɪk/" },
{ number: 403, english: "gorilla", spanish: "gorila", ipa: "/gəˈrɪl ə/" },
{ number: 404, english: "raccoon", spanish: "mapache", ipa: "/ræˈkun/" },
{ number: 405, english: "unicorn", spanish: "unicornio", ipa: "/ˈyu nɪˌkɔrn/" },
{ number: 406, english: "reindeer", spanish: "reno", ipa: "/ˈreɪnˌdɪər/" },
{ number: 407, english: "gill", spanish: "branquia", ipa: "/gɪl/" },
{ number: 408, english: "hippopotamus", spanish: "hipopótamo", ipa: "/ˌhɪp əˈpɒt ə məs/" },
{ number: 409, english: "grasshopper", spanish: "saltamontes", ipa: "/græs, grɑs ˈhɒp ər/" },
{ number: 410, english: "mouse", spanish: "ratón", ipa: "/maʊs/" },
{ number: 411, english: "fish", spanish: "pescado", ipa: "/fɪʃ/" },
{ number: 412, english: "rhinoceros", spanish: "rinoceronte", ipa: "/raɪˈnɒs ər əs/" },
{ number: 413, english: "horn", spanish: "cuerno", ipa: "/hɔrn/" },
{ number: 414, english: "turtle", spanish: "tortuga", ipa: "/ˈtɜr tl/" },
{ number: 415, english: "dentist", spanish: "dentista", ipa: "/ˈdɛn tɪst/" },
{ number: 416, english: "archaeologist", spanish: "arqueólogo", ipa: "/ˌɑr kiˈɒl ə dʒɪst/" },
{ number: 417, english: "juggler", spanish: "malabarista", ipa: "/ˈdʒʌg lər/" },
{ number: 418, english: "mechanic", spanish: "mecánico", ipa: "/məˈkæn ɪk/" },
{ number: 419, english: "waiter", spanish: "camarero", ipa: "/ˈweɪ tər/" },
{ number: 420, english: "winter", spanish: "invierno", ipa: "/ˈwɪn tər/" },
{ number: 421, english: "tornado", spanish: "tornado", ipa: "/tɔrˈneɪ doʊ/" },
{ number: 422, english: "bush", spanish: "arbusto", ipa: "/bʊʃ/" },
{ number: 423, english: "waterfall", spanish: "cascada", ipa: "/ˈwɔ tərˌfɔl, ˈwɒt ər-/" },
{ number: 424, english: "planet", spanish: "planeta", ipa: "/ˈplæn ɪt/" },
{ number: 425, english: "day", spanish: "día", ipa: "/deɪ/" },
{ number: 426, english: "avalanche", spanish: "avalancha", ipa: "/ˈæv əˌlæntʃ, -ˌlɑntʃ/" },
{ number: 427, english: "seed", spanish: "semilla", ipa: "/sid/" },
{ number: 428, english: "season", spanish: "temporada", ipa: "/ˈsi zən/" },
{ number: 429, english: "rain", spanish: "lluvia", ipa: "/reɪn/" },
{ number: 430, english: "bone", spanish: "hueso", ipa: "/boʊn/" },
{ number: 431, english: "hip", spanish: "cadera", ipa: "/hɪp/" },
{ number: 432, english: "hand", spanish: "mano", ipa: "/hænd/" },
{ number: 433, english: "nerve", spanish: "nervio", ipa: "/nɜrv/" },
{ number: 434, english: "mouth", spanish: "boca", ipa: "/maʊθ/" },
{ number: 435, english: "palm", spanish: "palma", ipa: "/pɑm/" },
{ number: 436, english: "peel", spanish: "piel", ipa: "/pil/" },
{ number: 437, english: "orange", spanish: "naranja", ipa: "/ˈɔr ɪndʒ, ˈɒr-/" },
{ number: 438, english: "wheat", spanish: "trigo", ipa: "/ʰwit, wit/" },
{ number: 439, english: "tomato", spanish: "tomate", ipa: "/təˈmeɪ toʊ, -ˈmɑ-/" },
{ number: 440, english: "school", spanish: "colegio, escuela", ipa: "/skul/" },
{ number: 441, english: "jetty", spanish: "embarcadero, muelle", ipa: "/ˈdʒɛt i/" },
{ number: 442, english: "shop", spanish: "tienda", ipa: "/ʃɒp/" },
{ number: 443, english: "anthill", spanish: "hormiguero", ipa: "/ˈæntˌhɪl/" },
{ number: 444, english: "wheelbarrow", spanish: "carretilla", ipa: "/ˈʰwilˌbær oʊ, ˈwil-/" },
{ number: 445, english: "lightning", spanish: "relámpago", ipa: "/ˈlaɪt nɪŋ/" },
{ number: 446, english: "brush", spanish: "cepillo", ipa: "/brʌʃ/" },
{ number: 447, english: "slingshot", spanish: "honda, cauchera, china", ipa: "/ˈslɪŋˌʃɒt/" },
{ number: 448, english: "kitchen", spanish: "cocina", ipa: "/ˈkɪtʃ ən/" },
{ number: 449, english: "candy", spanish: "caramelo", ipa: "/ˈkæn di/" },
{ number: 450, english: "monk", spanish: "monje", ipa: "/mʌŋk/" },
{ number: 451, english: "salt shaker", spanish: "salero", ipa: "/sɔlt ˈʃeɪ kər/" },
{ number: 452, english: "bowl", spanish: "cuenco, tazón", ipa: "/boʊl/" },
{ number: 453, english: "microphone", spanish: "micrófono", ipa: "/ˈmaɪ krəˌfoʊn/" },
{ number: 454, english: "brake", spanish: "freno", ipa: "/breɪk/" },
{ number: 455, english: "bakery", spanish: "panadería", ipa: "/ˈbeɪ kə ri, ˈbeɪk ri/" },
{ number: 456, english: "toothpaste", spanish: "pasta dental", ipa: "/ˈtuθˌpeɪst/" },
{ number: 457, english: "sweater", spanish: "suéter", ipa: "/ˈswɛt ər/" },
{ number: 458, english: "wolf", spanish: "lobo", ipa: "/wʊlf/" },
{ number: 459, english: "scarf", spanish: "bufanda", ipa: "/skɑrf/" },
{ number: 460, english: "swimmer", spanish: "nadador", ipa: "/swɪm/" },
{ number: 461, english: "limousine", spanish: "limusina", ipa: "/ˈlɪm əˌzin, ˌlɪm əˈzin/" },
{ number: 462, english: "town", spanish: "pueblo", ipa: "/taʊn/" },
{ number: 463, english: "salad", spanish: "ensalada", ipa: "/ˈsæl əd/" },
{ number: 464, english: "panties", spanish: "bragas, pantaletas", ipa: "/ˈpæn tiz/" },
{ number: 465, english: "sandwich", spanish: "emparedado", ipa: "/ˈsænd wɪtʃ, ˈsæn-/" },
{ number: 466, english: "raincoat", spanish: "impermeable", ipa: "/ˈreɪnˌkoʊt/" },
{ number: 467, english: "mummy", spanish: "momia", ipa: "/ˈmʌm i/" },
{ number: 468, english: "watchmaker", spanish: "relojero", ipa: "/ˈwɒtʃˌmeɪ kər/" },
{ number: 469, english: "tank", spanish: "tanque", ipa: "/tæŋk/" },
{ number: 471, english: "lipstick", spanish: "lápiz labial", ipa: "/ˈlɪpˌstɪk/" },
{ number: 470, english: "lettuce", spanish: "lechuga", ipa: "/ˈlɛt ɪs/" },
{ number: 472, english: "eggplant", spanish: "berenjena", ipa: "/ˈɛgˌplænt, -ˌplɑnt/" },
{ number: 473, english: "actor", spanish: "actor", ipa: "/ˈæk tər/" },
{ number: 474, english: "onion", spanish: "cebolla", ipa: "/ˈʌn yən/" },
{ number: 475, english: "spinach", spanish: "espinacas", ipa: "/ˈspɪn ɪtʃ/" },
{ number: 282, english: "bread", spanish: "pan", ipa: "/brɛd/" },
{ number: 476, english: "food", spanish: "comida", ipa: "/fud/" },
{ number: 479, english: "milk", spanish: "leche", ipa: "/mɪlk/" },
{ number: 480, english: "giraffe", spanish: "jirafa", ipa: "/dʒəˈræf/" },
{ number: 478, english: "ginger", spanish: "jengibre", ipa: "/ˈdʒɪn dʒər/" },
{ number: 477, english: "wine", spanish: "vino", ipa: "/waɪn/" },
{ number: 482, english: "photographer", spanish: "fotógrafo", ipa: "/fəˈtɒg rə fər/" },
{ number: 481, english: "pig", spanish: "cerdo", ipa: "/pɪg/" },
{ number: 483, english: "peanut", spanish: "maní", ipa: "/ˈpiˌnʌt, -nət/" },
{ number: 485, english: "sunflower", spanish: "girasol", ipa: "/ˈsʌnˌflaʊ ər/" },
{ number: 484, english: "pineapple", spanish: "piña", ipa: "/ˈpaɪˌnæp əl/" },
{ number: 486, english: "nail", spanish: "uña", ipa: "/neɪl/" },
{ number: 487, english: "torch", spanish: "antorcha", ipa: "/tɔrtʃ/" },
{ number: 488, english: "fire truck", spanish: "camión de bomberos", ipa: "/faɪər trʌk/" },
{ number: 489, english: "olive", spanish: "aceituna", ipa: "/ˈɒl ɪv/" },
{ number: 490, english: "window", spanish: "ventana", ipa: "/ˈwɪn doʊ/" },
{ number: 491, english: "armadillo", spanish: "armadillo", ipa: "/ˌɑr məˈdɪl oʊ/" },
{ number: 492, english: "asparagus", spanish: "espárragos", ipa: "/əˈspær ə gəs/" },
{ number: 493, english: "sole", spanish: "suela", ipa: "/soʊl/" },
{ number: 495, english: "bug", spanish: "bicho", ipa: "/bʌg/" },
{ number: 494, english: "cellphone", spanish: "teléfono móvil", ipa: "/ˈsɛlˌfoʊn/" },
{ number: 497, english: "stroller", spanish: "coche de bebe", ipa: "/ˈstroʊ lər/" },
{ number: 499, english: "beekeeper", spanish: "apicultor", ipa: "/ˈbiˌki pər/" },
{ number: 498, english: "celery", spanish: "apio", ipa: "/ˈsɛl ə ri, ˈsɛl ri/" },
{ number: 496, english: "journalist", spanish: "periodista", ipa: "/ˈdʒɜr nl ɪst/" },
{ number: 500, english: "hair clip", spanish: "pinza de pelo", ipa: "/hɛər klɪp/" },
{ number: 502, english: "paper clip", spanish: "clip de papel", ipa: "/ˈpeɪ pər klɪp/" },
{ number: 501, english: "plaster", spanish: "yeso", ipa: "/ˈplæs tər, ˈplɑ stər/" },
{ number: 503, english: "easel", spanish: "caballete", ipa: "/ˈi zəl/" },
{ number: 504, english: "die", spanish: "dado", ipa: "/daɪ/" },
{ number: 506, english: "artichoke", spanish: "alcachofa", ipa: "/ˈɑr tɪˌtʃoʊk/" },
{ number: 505, english: "pyramid", spanish: "pirámide", ipa: "/ˈpɪr ə mɪd/" },
{ number: 507, english: "banana", spanish: "plátano", ipa: "/bəˈnæn ə/" },
{ number: 508, english: "palette", spanish: "paleta", ipa: "/ˈpæl ɪt/" },
{ number: 511, english: "golf club", spanish: "palo de golf", ipa: "/gɒlf, gɔlf klʌb/" },
{ number: 510, english: "queen", spanish: "reina", ipa: "/kwin/" },
{ number: 509, english: "kiss", spanish: "beso", ipa: "/kɪs/" },
{ number: 512, english: "cake", spanish: "pastel", ipa: "/keɪk/" },
{ number: 513, english: "microscope", spanish: "microscopio", ipa: "/ˈmaɪ krəˌskoʊp/" },
{ number: 514, english: "mammoth", spanish: "mamut", ipa: "/ˈmæm əθ/" },
{ number: 515, english: "rolling pin", spanish: "rodillo", ipa: "/ˈroʊ lɪŋ pɪn/" },
{ number: 516, english: "death", spanish: "muerte", ipa: "/dɛθ/" },
{ number: 517, english: "paw", spanish: "pata", ipa: "/pɔ/" },
{ number: 518, english: "tiger", spanish: "tigre", ipa: "/ˈtaɪ gər/" },
{ number: 519, english: "checkers", spanish: "juego de damas", ipa: "/ˈtʃɛk ər/" },
{ number: 520, english: "castle", spanish: "castillo", ipa: "/ˈkæs əl, ˈkɑ səl/" },
{ number: 521, english: "iris", spanish: "iris", ipa: "/ˈaɪ rɪs/" },
{ number: 522, english: "french fries", spanish: "papas fritas", ipa: "/frɛntʃ fraɪz/" },
{ number: 523, english: "deer", spanish: "venado", ipa: "/dɪər/" },
{ number: 524, english: "pantyhose", spanish: "pantys", ipa: "/ˈpæn tiˌhoʊz/" },
{ number: 525, english: "raisins", spanish: "pasas", ipa: "/ˈreɪ zɪn/" },
{ number: 527, english: "root", spanish: "raíz", ipa: "/rut, rʊt/" },
{ number: 526, english: "igloo", spanish: "iglú", ipa: "/ˈɪg lu/" },
{ number: 528, english: "watch", spanish: "reloj", ipa: "/wɒtʃ/" },
{ number: 529, english: "doctor", spanish: "doctor", ipa: "/ˈdɒk tər/" },
{ number: 530, english: "guitar", spanish: "guitarra", ipa: "/gɪˈtɑr/" },
{ number: 531, english: "stocking", spanish: "media", ipa: "/ˈstɒk ɪŋ/" },
{ number: 532, english: "beach", spanish: "playa", ipa: "/bitʃ/" },
{ number: 533, english: "traffic light", spanish: "semáforo", ipa: "/ˈtræf ɪk laɪt/" },
{ number: 534, english: "detective", spanish: "detective", ipa: "/dɪˈtɛk tɪv/" },
{ number: 535, english: "intestine", spanish: "intestino", ipa: "/ɪnˈtɛs tɪn/" },
{ number: 537, english: "zebra", spanish: "cebra", ipa: "/ˈzi brə/" },
{ number: 538, english: "fountain", spanish: "fuente", ipa: "/ˈfaʊn tn/" },
{ number: 536, english: "hook", spanish: "gancho", ipa: "/hʊk/" },
{ number: 539, english: "band", spanish: "banda", ipa: "/bænd/" },
{ number: 540, english: "army", spanish: "ejército", ipa: "/ˈɑr mi/" },
{ number: 541, english: "cookie", spanish: "galleta", ipa: "/ˈkʊk i/" },
{ number: 542, english: "lawn mower", spanish: "cortacésped", ipa: "/lɔn ˈmoʊ ər/" },
{ number: 543, english: "chess", spanish: "ajedrez", ipa: "/tʃɛs/" },
{ number: 544, english: "baseball bat", spanish: "bate de béisbol", ipa: "/ˈbeɪsˌbɔl bæt/" },
{ number: 545, english: "carousel", spanish: "carrusel", ipa: "/ˌkær əˈsɛl, ˈkær əˌsɛl/" },
{ number: 546, english: "gull", spanish: "gaviota", ipa: "/gʌl/" },
{ number: 547, english: "subway", spanish: "subterraneo", ipa: "/ˈsʌbˌweɪ/" },
{ number: 549, english: "octopus", spanish: "pulpo", ipa: "/ˈɒk tə pəs/" },
{ number: 550, english: "thief", spanish: "ladrón", ipa: "/θif/" },
{ number: 548, english: "cart", spanish: "carro", ipa: "/kɑrt/" },
{ number: 551, english: "blackberry", spanish: "Mora", ipa: "/ˈblækˌbɛr i, -bə ri/" },
{ number: 552, english: "lamp", spanish: "lámpara", ipa: "/læmp/" },
{ number: 553, english: "tooth", spanish: "diente", ipa: "/tuθ/" },
{ number: 554, english: "dog", spanish: "perro", ipa: "/dɔg, dɒg/" },
{ number: 555, english: "ghost", spanish: "fantasma", ipa: "/goʊst/" },
{ number: 556, english: "plum", spanish: "ciruela", ipa: "/plʌm/" },
{ number: 557, english: "moon", spanish: "luna", ipa: "/mun/" },
{ number: 558, english: "sack", spanish: "saco", ipa: "/sæk/" },
{ number: 559, english: "belt", spanish: "cinturón", ipa: "/bɛlt/" },
{ number: 560, english: "pillow", spanish: "almohada", ipa: "/ˈpɪl oʊ/" },
{ number: 561, english: "hail", spanish: "granizo", ipa: "/heɪl/" },
{ number: 562, english: "handlebar", spanish: "manillar", ipa: "/ˈhæn dlˌbɑr/" },
{ number: 563, english: "peas", spanish: "guisante", ipa: "/pi/" },
{ number: 564, english: "welder", spanish: "soldador", ipa: "/wɛld/" },
{ number: 565, english: "choir", spanish: "coro", ipa: "/kwaɪər/" },
{ number: 566, english: "headphones", spanish: "auriculares", ipa: "/ˈhɛdˌfoʊn/" },
{ number: 567, english: "pharmacy", spanish: "farmacia", ipa: "/ˈfɑr mə si/" },
{ number: 568, english: "razor", spanish: "maquina de afeitar", ipa: "/ˈreɪ zər/" },
{ number: 569, english: "girl", spanish: "muchacha", ipa: "/gɜrl/" },
{ number: 570, english: "wild boar", spanish: "jabalí", ipa: "/waɪld bɔr, boʊr/" },
{ number: 571, english: "curb", spanish: "borde de acera", ipa: "/kɜrb/" },
{ number: 572, english: "ladle", spanish: "cucharón", ipa: "/ˈleɪd l/" },
{ number: 573, english: "binder", spanish: "carpeta de archivar", ipa: "/ˈbaɪn dər/" },
{ number: 574, english: "bunk bed", spanish: "litera", ipa: "/bʌŋk bɛd/" },
{ number: 575, english: "hairdresser", spanish: "peluquero", ipa: "/ˈhɛərˌdrɛs ər/" },
{ number: 576, english: "circus", spanish: "circo", ipa: "/ˈsɜr kəs/" },
{ number: 577, english: "fox", spanish: "zorro", ipa: "/fɒks/" },
{ number: 578, english: "bow", spanish: "arco", ipa: "/baʊ/" },
{ number: 579, english: "first aid", spanish: "primeros auxilios", ipa: "/fɜrst eɪd/" },
{ number: 580, english: "reed", spanish: "caña", ipa: "/rid/" },
{ number: 581, english: "alphabet", spanish: "alfabeto", ipa: "/ˈæl fəˌbɛt, -bɪt/" },
{ number: 582, english: "compass", spanish: "brújula, compas", ipa: "/ˈkʌm pəs/" },
{ number: 583, english: "penguin", spanish: "pingüino", ipa: "/ˈpɛŋ gwɪn, ˈpɛn-/" },
{ number: 584, english: "chimpanzee", spanish: "chimpancé", ipa: "/ˌtʃɪm pænˈzi/" },
{ number: 585, english: "astronomer", spanish: "astrónomo", ipa: "/əˈstrɒn ə mər/" },
{ number: 586, english: "cup", spanish: "copa, vaso", ipa: "/kʌp/" },
{ number: 587, english: "butter", spanish: "mantequilla", ipa: "/ˈbʌt ər/" },
{ number: 588, english: "wizard", spanish: "mago", ipa: "/ˈwɪz ərd/" },
{ number: 589, english: "vest", spanish: "chaleco", ipa: "/vɛst/" },
{ number: 590, english: "skull", spanish: "cráneo", ipa: "/skʌl/" },
{ number: 591, english: "snake", spanish: "serpiente", ipa: "/sneɪk/" },
{ number: 592, english: "mustache", spanish: "bigote", ipa: "/ˈmʌs tæʃ, məˈstæʃ/" },
{ number: 595, english: "lid", spanish: "tapa", ipa: "/lɪd/" },
{ number: 594, english: "corn", spanish: "maíz", ipa: "/kɔrn/" },
{ number: 593, english: "propeller", spanish: "hélice", ipa: "/prəˈpɛl ər/" },
{ number: 596, english: "cradle", spanish: "cuna", ipa: "/ˈkreɪd l/" },
{ number: 597, english: "earmuffs", spanish: "orejeras", ipa: "/ˈɪərˌmʌf/" },
{ number: 598, english: "button", spanish: "botón", ipa: "/ˈbʌt n/" },
{ number: 600, english: "piano", spanish: "piano", ipa: "/piˈæn oʊ, ˈpyæn oʊ/" },
{ number: 599, english: "bicycle", spanish: "bicicleta", ipa: "/ˈbaɪ sɪ kəl/" },
{ number: 601, english: "cape", spanish: "capa", ipa: "/keɪp/" },
{ number: 602, english: "cowboy", spanish: "vaquero", ipa: "/ˈkaʊˌbɔɪ/" },
{ number: 603, english: "flute", spanish: "flauta", ipa: "/flut/" },
{ number: 604, english: "streetcar", spanish: "tranvía", ipa: "/ˈstritˌkɑr/" },
{ number: 605, english: "cauliflower", spanish: "coliflor", ipa: "/ˈkɔ ləˌflaʊ ər/" },
{ number: 606, english: "laundry", spanish: "lavandería", ipa: "/ˈlɔn dri, ˈlɑn-/" },
{ number: 607, english: "back", spanish: "espalda", ipa: "/bæk/" },
{ number: 608, english: "traffic jam", spanish: "embotellamiento", ipa: "/ˈtræf ɪk dʒæm/" },
{ number: 609, english: "fairy", spanish: "hada", ipa: "/ˈfɛər i/" },
{ number: 610, english: "skeleton", spanish: "esqueleto", ipa: "/ˈskɛl ɪ tn/" },
{ number: 611, english: "soldier", spanish: "soldado", ipa: "/ˈsoʊl dʒər/" },
{ number: 612, english: "fireworks", spanish: "fuegos artificiales", ipa: "/ˈfaɪərˌwɜrk/" },
{ number: 613, english: "pitchfork", spanish: "horca", ipa: "/ˈpɪtʃˌfɔrk/" },
{ number: 614, english: "square", spanish: "cuadrado", ipa: "/skwɛər/" },
{ number: 615, english: "muzzle", spanish: "bozal", ipa: "/ˈmʌz əl/" },
{ number: 616, english: "spool", spanish: "carrete", ipa: "/spul/" },
{ number: 617, english: "swim fins", spanish: "aletas de natacion", ipa: "/swɪm fɪn/" },
{ number: 618, english: "rooster", spanish: "gallo", ipa: "/ˈru stər/" },
{ number: 619, english: "violin", spanish: "violín", ipa: "/ˌvaɪ əˈlɪn/" },
{ number: 620, english: "leaf", spanish: "hoja", ipa: "/lif/" },
{ number: 622, english: "apple", spanish: "manzana", ipa: "/ˈæp əl/" },
{ number: 623, english: "scarecrow", spanish: "espantapájaros", ipa: "/ˈskɛərˌkroʊ/" },
{ number: 624, english: "lumberjack", spanish: "leñador", ipa: "/ˈlʌm bərˌdʒæk/" },
{ number: 625, english: "chair", spanish: "silla", ipa: "/tʃɛər/" },
{ number: 626, english: "gift", spanish: "regalo", ipa: "/gɪft/" },
{ number: 621, english: "toy", spanish: "juguete", ipa: "/tɔɪ/" },
{ number: 627, english: "cannon", spanish: "cañón", ipa: "/ˈkæn ən/" },
{ number: 628, english: "night", spanish: "noche", ipa: "/naɪt/" },
{ number: 629, english: "ink", spanish: "tinta", ipa: "/ɪŋk/" },
{ number: 630, english: "chickpeas", spanish: "garbanzos", ipa: "/ˈtʃɪkˌpi/" },
{ number: 631, english: "box", spanish: "caja", ipa: "/bɒks/" },
{ number: 632, english: "crossword puzzle", spanish: "crucigrama", ipa: "/ˈkrɔsˌwɜrd ˈpʌz əl/" },
{ number: 633, english: "starfish", spanish: "estrella de mar", ipa: "/ˈstɑrˌfɪʃ/" },
{ number: 634, english: "elbow", spanish: "codo", ipa: "/ˈɛl boʊ/" },
{ number: 635, english: "stick", spanish: "palo", ipa: "/stɪk/" },
{ number: 636, english: "butcher", spanish: "carnicero", ipa: "/ˈbʊtʃ ər/" },
{ number: 637, english: "scales", spanish: "escamas", ipa: "/skeɪl/" },
{ number: 638, english: "horseshoe", spanish: "herradura", ipa: "/ˈhɔrsˌʃu, ˈhɔrʃ-/" },
{ number: 639, english: "washing machine", spanish: "lavadora", ipa: "/ˈwɒʃ ɪŋ  məˈʃin/" },
{ number: 640, english: "potato", spanish: "patata", ipa: "/pəˈteɪ toʊ, -tə/" },
{ number: 641, english: "coin", spanish: "moneda", ipa: "/kɔɪn/" },
{ number: 642, english: "path", spanish: "camino", ipa: "/pæθ, pɑθ/" },
{ number: 643, english: "hairbrush", spanish: "cepillo para el pelo", ipa: "/ˈhɛərˌbrʌʃ/" },
{ number: 644, english: "ointment", spanish: "ungüento", ipa: "/ˈɔɪnt mənt/" },
{ number: 645, english: "pupil", spanish: "alumno", ipa: "/ˈpyu pəl/" },
{ number: 646, english: "scorpion", spanish: "escorpión", ipa: "/ˈskɔr pi ən/" },
{ number: 647, english: "eyelash", spanish: "pestaña", ipa: "/ˈaɪˌlæʃ/" },
{ number: 648, english: "pianist", spanish: "pianista", ipa: "/piˈæn ɪst, ˈpyæn-, ˈpi ə nɪst/" },
{ number: 649, english: "sunrise", spanish: "amanecer", ipa: "/ˈsʌnˌraɪz/" },
{ number: 650, english: "head", spanish: "cabeza", ipa: "/hɛd/" },
{ number: 651, english: "radish", spanish: "rábano", ipa: "/ˈræd ɪʃ/" },
{ number: 652, english: "sewing machine", spanish: "máquina de coser", ipa: "/ˈsoʊ ɪŋ məˈʃin/" },
{ number: 653, english: "grass", spanish: "césped", ipa: "/græs, grɑs/" },
{ number: 654, english: "eggshell", spanish: "cáscara de huevo", ipa: "/ˈɛgˌʃɛl/" },
{ number: 655, english: "broccoli", spanish: "brócoli", ipa: "/ˈbrɒk ə li, ˈbrɒk li/" },
{ number: 656, english: "wave", spanish: "ola", ipa: "/weɪv/" },
{ number: 657, english: "field", spanish: "campo", ipa: "/fild/" },
{ number: 658, english: "knee", spanish: "rodilla", ipa: "/ni/" },
{ number: 659, english: "pond", spanish: "estanque", ipa: "/pɒnd/" },
{ number: 660, english: "fountain pen", spanish: "pluma (antigua)", ipa: "/ˈfaʊn tn pɛn/" },
{ number: 661, english: "canoe", spanish: "canoa", ipa: "/kəˈnu/" },
{ number: 662, english: "beer", spanish: "cerveza", ipa: "/bɪər/" },
{ number: 663, english: "nest", spanish: "nido", ipa: "/nɛst/" },
{ number: 664, english: "letters", spanish: "letras", ipa: "/ˈlɛt ər/" },
{ number: 665, english: "burrow", spanish: "madriguera", ipa: "/ˈbɜr oʊ, ˈbʌr oʊ/" },
{ number: 666, english: "vulture", spanish: "buitre", ipa: "/ˈvʌl tʃər/" },
{ number: 667, english: "sneakers", spanish: "zapatillas", ipa: "/ˈsni kər/" },
{ number: 668, english: "glue", spanish: "pegamento", ipa: "/glu/" },
{ number: 669, english: "surgeon", spanish: "cirujano", ipa: "/ˈsɜr dʒən/" },
{ number: 670, english: "skater", spanish: "patinador", ipa: "/ˈskeɪ tər/" },
{ number: 671, english: "dinosaur", spanish: "dinosaurio", ipa: "/ˈdaɪ nəˌsɔr/" },
{ number: 672, english: "fingerprint", spanish: "huella dactilar", ipa: "/ˈfɪŋ gərˌprɪnt/" },
{ number: 673, english: "crocodile", spanish: "cocodrilo", ipa: "/ˈkrɒk əˌdaɪl/" },
{ number: 674, english: "boxer", spanish: "boxer", ipa: "/ˈbɒk sər/" },
{ number: 675, english: "muscle", spanish: "músculo", ipa: "/ˈmʌs əl/" },
{ number: 677, english: "shopping car", spanish: "carrito de la compra", ipa: "/ˈʃɒp ɪŋ kɑr/" },
{ number: 678, english: "ponytail", spanish: "cola de caballo", ipa: "/ˈpoʊ niˌteɪl/" },
{ number: 679, english: "branch", spanish: "rama", ipa: "/bræntʃ, brɑntʃ/" },
{ number: 680, english: "rocket", spanish: "cohete", ipa: "/ˈrɒk ɪt/" },
{ number: 681, english: "constellation", spanish: "constelación", ipa: "/ˌkɒn stəˈleɪ ʃən/" },
{ number: 682, english: "yarn", spanish: "hilo (tejer)", ipa: "/yɑrn/" },
{ number: 683, english: "wrench", spanish: "llave inglesa", ipa: "/rɛntʃ/" },
{ number: 676, english: "smoke", spanish: "humo", ipa: "/smoʊk/" },
{ number: 684, english: "farm", spanish: "granja", ipa: "/fɑrm/" },
{ number: 685, english: "bus stop", spanish: "parada de autobús", ipa: "/bʌs stɒp/" },
{ number: 686, english: "florist", spanish: "florista", ipa: "/ˈflɔr ɪst, ˈfloʊr-, ˈflɒr-/" },
{ number: 687, english: "chain", spanish: "cadena", ipa: "/tʃeɪn/" },
{ number: 688, english: "prisoner", spanish: "prisionero", ipa: "/ˈprɪz ə nər, ˈprɪz nər/" },
{ number: 689, english: "sponge", spanish: "esponja", ipa: "/spʌndʒ/" },
{ number: 690, english: "dragonfly", spanish: "libélula", ipa: "/ˈdræg ənˌflaɪ/" },
{ number: 691, english: "map", spanish: "mapa", ipa: "/mæp/" },
{ number: 692, english: "mailbox", spanish: "buzón", ipa: "/ˈmeɪlˌbɒks/" },
{ number: 693, english: "seal", spanish: "sello", ipa: "/sil/" },
{ number: 694, english: "lion", spanish: "león", ipa: "/ˈlaɪ ən/" },
{ number: 695, english: "triangle", spanish: "triángulo", ipa: "/ˈtraɪˌæŋ gəl/" },
{ number: 696, english: "factory", spanish: "fábrica", ipa: "/ˈfæk tə ri, -tri/" },
{ number: 697, english: "firefighter", spanish: "bombero", ipa: "/ˈfaɪərˌfaɪ tɛr/" },
{ number: 698, english: "pan", spanish: "sarten", ipa: "/pæn/" },
{ number: 699, english: "clock", spanish: "reloj", ipa: "/klɒk/" },
{ number: 700, english: "ambulance", spanish: "ambulancia", ipa: "/ˈæm byə ləns/" },
{ number: 701, english: "waitress", spanish: "camarera", ipa: "/ˈweɪ trɪs/" },
{ number: 702, english: "shelf", spanish: "estante", ipa: "/ʃɛlf/" },
{ number: 703, english: "jewel", spanish: "joya", ipa: "/ˈdʒu əl/" },
{ number: 704, english: "chin", spanish: "barbilla", ipa: "/tʃɪn/" },
{ number: 705, english: "floor", spanish: "piso", ipa: "/flɔr, floʊr/" },
{ number: 706, english: "pacifier", spanish: "chupete", ipa: "/ˈpæs əˌfaɪ ər/" },
{ number: 707, english: "comet", spanish: "cometa espacial", ipa: "/ˈkɒm ɪt/" },
{ number: 708, english: "fisherman", spanish: "pescador", ipa: "/ˈfɪʃ ər mən/" },
{ number: 709, english: "pool", spanish: "piscina", ipa: "/pul/" },
{ number: 710, english: "maze", spanish: "laberinto", ipa: "/meɪz/" },
{ number: 711, english: "cashier", spanish: "cajero", ipa: "/kæˈʃɪər/" },
{ number: 712, english: "barrel", spanish: "barril", ipa: "/ˈbær əl/" },
{ number: 713, english: "rice", spanish: "arroz", ipa: "/raɪs/" },
{ number: 714, english: "mask", spanish: "máscara", ipa: "/mæsk, mɑsk/" },
{ number: 715, english: "sandbox", spanish: "caja de arena", ipa: "/ˈsændˌbɒks/" },
{ number: 716, english: "elephant", spanish: "elefante", ipa: "/ˈɛl ə fənt/" },
{ number: 717, english: "duck", spanish: "pato", ipa: "/dʌk/" },
{ number: 718, english: "truck", spanish: "camión", ipa: "/trʌk/" },
{ number: 719, english: "rock", spanish: "roca", ipa: "/rɒk/" },
{ number: 720, english: "hanger", spanish: "percha", ipa: "/ˈhæŋ ər/" },
{ number: 721, english: "mantis", spanish: "mantis", ipa: "/ˈmæn tɪs/" },
{ number: 722, english: "sugar", spanish: "azúcar", ipa: "/ˈʃʊg ər/" },
{ number: 723, english: "heart", spanish: "corazón", ipa: "/hɑrt/" },
{ number: 724, english: "road", spanish: "carretera", ipa: "/roʊd/" },
{ number: 725, english: "dune", spanish: "duna", ipa: "/dun, dyun/" },
{ number: 726, english: "goat", spanish: "cabra", ipa: "/goʊt/" },
{ number: 727, english: "cupcake", spanish: "cup cake", ipa: "/ˈkʌpˌkeɪk/" },
{ number: 728, english: "writer", spanish: "escritor", ipa: "/ˈraɪ tər/" },
{ number: 729, english: "toolbox", spanish: "caja de instrumento", ipa: "/ˈtulˌbɒks/" },
{ number: 730, english: "goggles", spanish: "gafas de protección", ipa: "/ˈgɒg əl/" },
{ number: 731, english: "towel", spanish: "toalla", ipa: "/ˈtaʊ əl, taʊl/" },
{ number: 732, english: "garage", spanish: "garaje", ipa: "/gəˈrɑʒ, -ˈrɑdʒ/" },
{ number: 733, english: "chocolate", spanish: "chocolate", ipa: "/ˈtʃɔ kə lɪt/" },
{ number: 734, english: "shrimp", spanish: "camarón", ipa: "/ʃrɪmp/" },
{ number: 735, english: "navel", spanish: "ombligo", ipa: "/ˈneɪ vəl/" },
{ number: 736, english: "hoof", spanish: "casco", ipa: "/hʊf, huf/" },
{ number: 737, english: "throne", spanish: "trono", ipa: "/θroʊn/" },
{ number: 738, english: "skyscraper", spanish: "rascacielos", ipa: "/ˈskaɪˌskreɪ pər/" },
{ number: 739, english: "brook", spanish: "arroyo", ipa: "/brʊk/" },
{ number: 740, english: "sandals", spanish: "sandalias", ipa: "/ˈsæn dl/" },
{ number: 741, english: "bottle", spanish: "botella", ipa: "/ˈbɒt l/" },
{ number: 742, english: "otter", spanish: "nutria", ipa: "/ˈɒt ər/" },
{ number: 743, english: "nose", spanish: "nariz", ipa: "/noʊz/" },
{ number: 744, english: "star", spanish: "estrella", ipa: "/stɑr/" },
{ number: 745, english: "toe", spanish: "dedo del pie", ipa: "/toʊ/" },
{ number: 746, english: "north", spanish: "norte", ipa: "/nɔrθ/" },
{ number: 747, english: "frog", spanish: "rana", ipa: "/frɒg, frɔg/" },
{ number: 748, english: "faucet", spanish: "grifo", ipa: "/ˈfɔ sɪt/" },
{ number: 749, english: "soccer goal", spanish: "gol", ipa: "/ˈsɒk ər goʊl/" },
{ number: 750, english: "roof", spanish: "techo", ipa: "/ruf, rʊf/" },
{ number: 751, english: "dome", spanish: "cúpula", ipa: "/doʊm/" },
{ number: 752, english: "tower", spanish: "torre", ipa: "/ˈtaʊ ər/" },
{ number: 753, english: "sand", spanish: "arena", ipa: "/sænd/" },
{ number: 754, english: "paint", spanish: "pintura", ipa: "/peɪnt/" },
{ number: 755, english: "fireplace", spanish: "chimenea", ipa: "/ˈfaɪərˌpleɪs/" },
{ number: 756, english: "spoon", spanish: "cuchara", ipa: "/spun/" },
{ number: 757, english: "cage", spanish: "jaula", ipa: "/keɪdʒ/" },
{ number: 758, english: "stairs", spanish: "escalera", ipa: "/stɛər/" },
{ number: 759, english: "roof tile", spanish: "teja", ipa: "/ruf, rʊf taɪl/" },
{ number: 760, english: "shovel", spanish: "pala", ipa: "/ˈʃʌv əl/" },
{ number: 762, english: "king", spanish: "rey", ipa: "/kɪŋ/" },
{ number: 761, english: "tape", spanish: "cinta adhesiva", ipa: "/teɪp/" },
{ number: 763, english: "diaper", spanish: "pañal", ipa: "/ˈdaɪ pər, ˈdaɪ ə pər/" },
{ number: 764, english: "stamp", spanish: "sello", ipa: "/stæmp/" },
{ number: 765, english: "trailer", spanish: "remolque", ipa: "/ˈtreɪ lər/" },
{ number: 766, english: "tail", spanish: "cola", ipa: "/teɪl/" },
{ number: 767, english: "dragon", spanish: "dragón", ipa: "/ˈdræg ən/" },
{ number: 768, english: "undershirt", spanish: "camiseta", ipa: "/ˈʌn dərˌʃɜrt/" },
{ number: 769, english: "saber", spanish: "sable", ipa: "/ˈseɪ bər/" },
{ number: 770, english: "scuba diver", spanish: "buzo", ipa: "/ˈsku bə ˈdaɪ vər/" },
{ number: 771, english: "bracelet", spanish: "pulsera", ipa: "/ˈbreɪs lɪt/" },
{ number: 772, english: "mannequin", spanish: "maniquí", ipa: "/ˈmæn ɪ kɪn/" },
{ number: 773, english: "sled", spanish: "trineo", ipa: "/slɛd/" },
{ number: 774, english: "gun", spanish: "pistola", ipa: "/gʌn/" },
{ number: 775, english: "saw", spanish: "sierra", ipa: "/sɔ/" },
{ number: 776, english: "coffee", spanish: "café", ipa: "/ˈkɔ fi, ˈkɒf i/" },
{ number: 777, english: "clown", spanish: "payaso", ipa: "/klaʊn/" },
{ number: 778, english: "hair drier", spanish: "secadora de pelo", ipa: "/hɛər ˈdraɪ ər/" },
{ number: 779, english: "drug", spanish: "medicina, droga", ipa: "/drʌg/" },
{ number: 780, english: "flower", spanish: "flor", ipa: "/ˈflaʊ ər/" },
{ number: 781, english: "sunset", spanish: "la puesta del sol", ipa: "/ˈsʌnˌsɛt/" },
{ number: 782, english: "car", spanish: "coche", ipa: "/kɑr/" },
{ number: 783, english: "cook", spanish: "cocinar", ipa: "/kʊk/" },
{ number: 784, english: "ladder", spanish: "escalera", ipa: "/ˈlæd ər/" },
{ number: 785, english: "gas station", spanish: "gasolinera", ipa: "/gæs ˈsteɪ ʃən/" },
{ number: 786, english: "stadium", spanish: "estadio", ipa: "/ˈsteɪ di əm/" },
{ number: 787, english: "beads", spanish: "rosario", ipa: "/bid/" },
{ number: 788, english: "fence", spanish: "cerca", ipa: "/fɛns/" },
{ number: 789, english: "granddaughter", spanish: "nieta", ipa: "/ˈgrænˌdɔ tər/" },
{ number: 790, english: "grandson", spanish: "nieto", ipa: "/ˈgrænˌsʌn, ˈgrænd-/" },
{ number: 791, english: "tadpole", spanish: "renacuajo", ipa: "/ˈtæd poʊl/" },
{ number: 792, english: "beehive", spanish: "colmena", ipa: "/ˈbiˌhaɪv/" },
{ number: 793, english: "keyboard", spanish: "teclado", ipa: "/ˈkiˌbɔrd, -ˌboʊrd/" },
{ number: 794, english: "world", spanish: "mundo", ipa: "/wɜrld/" },
{ number: 795, english: "table", spanish: "mesa", ipa: "/ˈteɪ bəl/" },
{ number: 796, english: "goblet", spanish: "copa", ipa: "/ˈgɒb lɪt/" },
{ number: 797, english: "game", spanish: "juego", ipa: "/geɪm/" },
{ number: 798, english: "breasts", spanish: "pechos", ipa: "/brɛst/" },
{ number: 799, english: "cheese", spanish: "queso", ipa: "/tʃiz/" },
{ number: 800, english: "surfboard", spanish: "tabla de surf", ipa: "/ˈsɜrfˌbɔrd, -ˌboʊrd/" },
{ number: 801, english: "wheel", spanish: "rueda", ipa: "/ʰwil, wil/" },
{ number: 802, english: "eye doctor", spanish: "oculista", ipa: "/aɪ ˈdɒk tər/" },
{ number: 803, english: "candle", spanish: "vela", ipa: "/ˈkæn dl/" },
{ number: 805, english: "bra", spanish: "sostén", ipa: "/brɑ/" },
{ number: 806, english: "forest", spanish: "bosque", ipa: "/ˈfɔr ɪst, ˈfɒr-/" },
{ number: 807, english: "desert", spanish: "desierto", ipa: "/ˈdɛz ərt/" },
{ number: 808, english: "chemist", spanish: "químico", ipa: "/ˈkɛm ɪst/" },
{ number: 809, english: "clover", spanish: "trébol", ipa: "/ˈkloʊ vər/" },
{ number: 810, english: "switch", spanish: "swiche", ipa: "/swɪtʃ/" },
{ number: 811, english: "bullet", spanish: "bala", ipa: "/ˈbʊl ɪt/" },
{ number: 812, english: "kitten", spanish: "gatito", ipa: "/ˈkɪt n/" },
{ number: 813, english: "swivel chair", spanish: "silla giratoria", ipa: "/ˈswɪv əl tʃɛər/" },
{ number: 814, english: "collar", spanish: "collar", ipa: "/ˈkɒl ər/" },
{ number: 815, english: "acrobat", spanish: "acróbata", ipa: "/ˈæk rəˌbæt/" },
{ number: 816, english: "harp", spanish: "arpa", ipa: "/hɑrp/" },
{ number: 817, english: "tripod", spanish: "trípode", ipa: "/ˈtraɪ pɒd/" },
{ number: 818, english: "shark", spanish: "tiburón", ipa: "/ʃɑrk/" },
{ number: 819, english: "calendar", spanish: "calendario", ipa: "/ˈkæl ən dər/" },
{ number: 820, english: "raft", spanish: "balsa", ipa: "/ræft, rɑft/" },
{ number: 821, english: "radiator", spanish: "radiador", ipa: "/ˈreɪ diˌeɪ tər/" },
{ number: 822, english: "jar", spanish: "tarro", ipa: "/dʒɑr/" },
{ number: 823, english: "bag", spanish: "bolso", ipa: "/bæg/" },
{ number: 824, english: "beetle", spanish: "escarabajo", ipa: "/ˈbit l/" },
{ number: 804, english: "sword", spanish: "espada", ipa: "/sɔrd, soʊrd/" },
{ number: 825, english: "desk", spanish: "escritorio", ipa: "/dɛsk/" },
{ number: 826, english: "shoemaker", spanish: "zapatero", ipa: "/ˈʃuˈmeɪ kər/" },
{ number: 827, english: "gold", spanish: "oro", ipa: "/goʊld/" },
{ number: 829, english: "notebook", spanish: "cuaderno", ipa: "/ˈnoʊtˌbʊk/" },
{ number: 830, english: "camel", spanish: "camello", ipa: "/ˈkæm əl/" },
{ number: 828, english: "barbell", spanish: "barra con pesas", ipa: "/ˈbɑrˌbɛl/" },
{ number: 831, english: "butterfly", spanish: "mariposa", ipa: "/ˈbʌt ərˌflaɪ/" },
{ number: 832, english: "bed", spanish: "cama", ipa: "/bɛd/" },
{ number: 834, english: "flight", spanish: "vuelo", ipa: "/flaɪt/" },
{ number: 835, english: "taxi", spanish: "taxi", ipa: "/ˈtæk si/" },
{ number: 837, english: "reservation", spanish: "reserva", ipa: "/ˌrɛz ərˈveɪ ʃən/" },
{ number: 836, english: "hotel", spanish: "hotel", ipa: "/hoʊˈtɛl/" },
{ number: 833, english: "passport", spanish: "pasaporte", ipa: "/ˈpæs pɔrt, -poʊrt, ˈpɑs-/" },
{ number: 838, english: "newspaper", spanish: "periódico", ipa: "/ˈnuzˌpeɪ pər/" },
{ number: 839, english: "restaurant", spanish: "restaurante", ipa: "/ˈrɛs tər ənt/" },
{ number: 840, english: "bathroom", spanish: "baño", ipa: "/ˈbæθˌrum, -ˌrʊm, ˈbɑθ-/" },
{ number: 843, english: "check", spanish: "cuenta (restaurant)", ipa: "/tʃɛk/" },
{ number: 844, english: "child", spanish: "niño", ipa: "/tʃaɪld/" },
{ number: 842, english: "meat", spanish: "carne", ipa: "/mit/" },
{ number: 841, english: "menu", spanish: "menú", ipa: "/ˈmɛn yu, ˈmeɪ nyu/" },
{ number: 845, english: "family", spanish: "familia", ipa: "/ˈfæm ə li, ˈfæm li/" },
{ number: 846, english: "mother", spanish: "madre", ipa: "/ˈmʌð ər/" },
{ number: 847, english: "father", spanish: "padre", ipa: "/ˈfɑ ðər/" },
{ number: 848, english: "husband", spanish: "marido", ipa: "/ˈhʌz bənd/" },
{ number: 849, english: "wife", spanish: "esposa", ipa: "/waɪf/" },
{ number: 850, english: "brother", spanish: "hermano", ipa: "/ˈbrʌð ər/" },
{ number: 851, english: "dad", spanish: "papá", ipa: "/dæd/" },
{ number: 852, english: "mom", spanish: "mamá", ipa: "/mɒm/" },
{ number: 853, english: "son", spanish: "hijo", ipa: "/sʌn/" },
{ number: 855, english: "shoe", spanish: "zapato", ipa: "/ʃu/" },
{ number: 854, english: "daughter", spanish: "hija", ipa: "/ˈdɔ tər/" },
{ number: 856, english: "pant", spanish: "pantalón", ipa: "/pænt/" },
{ number: 858, english: "pen", spanish: "bolígrafo", ipa: "/pɛn/" },
{ number: 859, english: "professor", spanish: "profesor", ipa: "/prəˈfɛs ər/" },
{ number: 857, english: "class", spanish: "clase", ipa: "/klæs, klɑs/" },
{ number: 860, english: "idea", spanish: "idea", ipa: "/aɪˈdi ə, aɪˈdiə/" },
{ number: 861, english: "word", spanish: "palabra", ipa: "/wɜrd/" },
{ number: 862, english: "woman", spanish: "mujer", ipa: "/ˈwʊm ən/" },
{ number: 863, english: "horse", spanish: "caballo", ipa: "/hɔrs/" },
{ number: 864, english: "embassy", spanish: "embajada", ipa: "/ˈɛm bə si/" },
{ number: 865, english: "cat", spanish: "gato", ipa: "/kæt/" },
{ number: 866, english: "zoo", spanish: "zoo", ipa: "/zu/" },
{ number: 867, english: "west", spanish: "oeste", ipa: "/wɛst/" },
{ number: 868, english: "lips", spanish: "labios", ipa: "/lɪp/" },
{ number: 869, english: "skin", spanish: "piel", ipa: "/skɪn/" },
{ number: 870, english: "tongue", spanish: "lengua", ipa: "/tʌŋ/" },
{ number: 871, english: "police", spanish: "policía", ipa: "/pəˈlis/" },
{ number: 872, english: "blood", spanish: "sangre", ipa: "/blʌd/" },
{ number: 873, english: "emergency", spanish: "emergencia", ipa: "/ɪˈmɜr dʒən si/" },
{ number: 874, english: "dress", spanish: "vestir", ipa: "/drɛs/" },
{ number: 875, english: "inside", spanish: "dentro", ipa: "/ˈɪnˈsaɪd/" },
{ number: 876, english: "boss", spanish: "jefe", ipa: "/bɔs, bɒs/" },
{ number: 877, english: "officer", spanish: "oficial", ipa: "/ˈɔ fə sər, ˈɒf ə-/" },
{ number: 878, english: "director", spanish: "director", ipa: "/dɪˈrɛk tər, daɪ-/" },
{ number: 879, english: "secretary", spanish: "secretario", ipa: "/ˈsɛk rɪˌtɛr i/" },
{ number: 880, english: "sauce", spanish: "salsa", ipa: "/sɔs/" },
{ number: 881, english: "honey", spanish: "miel", ipa: "/ˈhʌn i/" },
{ number: 882, english: "tuna", spanish: "atún", ipa: "/ˈtu nə, ˈtyu-/" },
{ number: 883, english: "lunch", spanish: "almuerzo", ipa: "/lʌntʃ/" },
{ number: 884, english: "dinner", spanish: "cena", ipa: "/ˈdɪn ər/" },
{ number: 886, english: "judge", spanish: "juez", ipa: "/dʒʌdʒ/" },
{ number: 885, english: "beef", spanish: "carne de vaca", ipa: "/bif/" },
{ number: 888, english: "lawyer", spanish: "abogado", ipa: "/ˈlɔ yər, ˈlɔɪ ər/" },
{ number: 887, english: "author", spanish: "autor", ipa: "/ˈɔ θər/" },
{ number: 889, english: "worker", spanish: "obrero", ipa: "/ˈwɜr kər/" },
{ number: 890, english: "professional", spanish: "profesional", ipa: "/prəˈfɛʃ ə nl/" },
{ number: 891, english: "animal", spanish: "animal", ipa: "/ˈæn ə məl/" },
{ number: 892, english: "profession", spanish: "profesión", ipa: "/prəˈfɛʃ ən/" },
{ number: 893, english: "time", spanish: "hora", ipa: "/taɪm/" },
{ number: 894, english: "date", spanish: "fecha", ipa: "/deɪt/" },
{ number: 896, english: "birth", spanish: "nacimiento", ipa: "/bɜrθ/" },
{ number: 895, english: "century", spanish: "siglo", ipa: "/ˈsɛn tʃə ri/" },
{ number: 897, english: "period", spanish: "período", ipa: "/ˈpɪər i əd/" },
{ number: 898, english: "summer", spanish: "el verano", ipa: "/ˈsʌm ər/" },
{ number: 899, english: "evening", spanish: "noche", ipa: "/ˈiv nɪŋ/" },
{ number: 900, english: "second", spanish: "segundo", ipa: "/ˈsɛk ənd/" },
{ number: 902, english: "pasta", spanish: "pastas", ipa: "/ˈpɑ stə/" },
{ number: 901, english: "stage", spanish: "escenario", ipa: "/steɪdʒ/" },
{ number: 903, english: "chicken", spanish: "pollo", ipa: "/ˈtʃɪk ən/" },
{ number: 905, english: "answer", spanish: "respuesta", ipa: "/ˈæn sər, ˈɑn-/" },
{ number: 904, english: "plate", spanish: "plato", ipa: "/pleɪt/" },
{ number: 906, english: "soup", spanish: "sopa", ipa: "/sup/" },
{ number: 907, english: "breakfast", spanish: "desayuno", ipa: "/ˈbrɛk fəst/" },
{ number: 908, english: "pork", spanish: "cerdo", ipa: "/pɔrk, poʊrk/" },
{ number: 909, english: "oil", spanish: "petróleo", ipa: "/ɔɪl/" },
{ number: 910, english: "color", spanish: "color", ipa: "/ˈkʌl ər/" },
{ number: 911, english: "friend", spanish: "amigo", ipa: "/frɛnd/" },
{ number: 912, english: "uncle", spanish: "tío", ipa: "/ˈʌŋ kəl/" },
{ number: 913, english: "house", spanish: "casa", ipa: "/haʊs/" },
{ number: 914, english: "party", spanish: "fiesta", ipa: "/ˈpɑr ti/" },
{ number: 915, english: "bird", spanish: "pájaro", ipa: "/bɜrd/" },
{ number: 916, english: "name", spanish: "nombre", ipa: "/neɪm/" },
{ number: 917, english: "women", spanish: "mujer", ipa: "/ˈwɪm ɪn/" },
{ number: 918, english: "job", spanish: "trabajo", ipa: "/dʒɒb/" },
{ number: 919, english: "student", spanish: "estudiante", ipa: "/ˈstud nt, ˈstyud-/" },
{ number: 920, english: "parent", spanish: "padre", ipa: "/ˈpɛər ənt, ˈpær-/" },
{ number: 921, english: "sister", spanish: "hermana", ipa: "/ˈsɪs tər/" },
{ number: 922, english: "radio", spanish: "radio", ipa: "/ˈreɪ diˌoʊ/" },
{ number: 923, english: "wall", spanish: "pared", ipa: "/wɔl/" },
{ number: 924, english: "cabinet", spanish: "gabinete", ipa: "/ˈkæb ə nɪt/" },
{ number: 925, english: "telephone", spanish: "teléfono", ipa: "/ˈtɛl əˌfoʊn/" },
{ number: 927, english: "country", spanish: "país", ipa: "/ˈkʌn tri/" },
{ number: 926, english: "screen", spanish: "pantalla", ipa: "/skrin/" },
{ number: 928, english: "center", spanish: "centro", ipa: "/ˈsɛn tər/" },
{ number: 929, english: "border", spanish: "frontera", ipa: "/ˈbɔr dər/" },
{ number: 930, english: "valley", spanish: "valle", ipa: "/ˈvæl i/" },
{ number: 931, english: "route", spanish: "ruta", ipa: "/rut, raʊt/" },
{ number: 932, english: "model", spanish: "modelo", ipa: "/ˈmɒd l/" },
{ number: 933, english: "afternoon", spanish: "tarde", ipa: "/<ˌæf tərˈnun, ˌɑf-/" },
{ number: 934, english: "decade", spanish: "década", ipa: "/ˈdɛk eɪd/" },
{ number: 935, english: "home", spanish: "hogar", ipa: "/hoʊm/" },
{ number: 936, english: "office", spanish: "oficina", ipa: "/ˈɔ fɪs, ˈɒf ɪs/" },
{ number: 937, english: "average", spanish: "promedio", ipa: "/ˈæv ər ɪdʒ, ˈæv rɪdʒ/" },
{ number: 938, english: "half", spanish: "mitad", ipa: "/hæf, hɑf/" },
{ number: 939, english: "meal", spanish: "comida", ipa: "/mil/" },
{ number: 940, english: "university", spanish: "universidad", ipa: "/ˌyu nəˈvɜr sɪ ti/" },
{ number: 941, english: "test", spanish: "prueba", ipa: "/tɛst/" },
{ number: 942, english: "document", spanish: "documento", ipa: "/ˈdɒk yə mənt/" },
{ number: 943, english: "course", spanish: "curso", ipa: "/kɔrs, koʊrs/" },
{ number: 944, english: "presentation", spanish: "presentación", ipa: "/ˌprɛz ənˈteɪ ʃən/" },
{ number: 945, english: "institute", spanish: "instituto", ipa: "/ˈɪn stɪˌtut, -ˌtyut/" },
{ number: 946, english: "pair", spanish: "par", ipa: "/pɛr/" },
{ number: 947, english: "TV", spanish: "televisión", ipa: "/ˈtiˈvi/" },
{ number: 948, english: "television", spanish: "televisión", ipa: "/ˈtɛl əˌvɪʒ ən/" },
{ number: 949, english: "hour", spanish: "hora", ipa: "/aʊər, ˈaʊ ər/" },
{ number: 951, english: "illness", spanish: "enfermedad", ipa: "/ˈɪl nɪs/" },
{ number: 952, english: "sight", spanish: "visión", ipa: "/saɪt/" },
{ number: 953, english: "accident", spanish: "accidente", ipa: "/ˈæk sɪ dənt/" },
{ number: 950, english: "aunt", spanish: "tía", ipa: "/ænt, ɑnt/" },
{ number: 954, english: "material", spanish: "material", ipa: "/məˈtɪər i əl/" },
{ number: 955, english: "faith", spanish: "fe", ipa: "/feɪθ/" },
{ number: 956, english: "exit", spanish: "salida", ipa: "/ˈɛg zɪt, ˈɛk sɪt/" },
{ number: 957, english: "murder", spanish: "asesinato", ipa: "/ˈmɜr dər/" },
{ number: 958, english: "shape", spanish: "forma", ipa: "/ʃeɪp/" },
{ number: 959, english: "danger", spanish: "peligro", ipa: "/ˈdeɪn dʒər/" },
{ number: 960, english: "interest", spanish: "interes", ipa: "/ˈɪn tər ɪst, -trɪst/" },
{ number: 961, english: "strength", spanish: "fuerza", ipa: "/strɛŋkθ, strɛŋθ, strɛnθ/" },
{ number: 962, english: "tradition", spanish: "tradición", ipa: "/trəˈdɪʃ ən/" },
{ number: 963, english: "relation", spanish: "relación", ipa: "/rɪˈleɪ ʃən/" },
{ number: 964, english: "distance", spanish: "distancia", ipa: "/ˈdɪs təns/" },
{ number: 965, english: "depth", spanish: "profundidad", ipa: "/dɛpθ/" },
{ number: 966, english: "task", spanish: "tarea", ipa: "/tæsk, tɑsk/" },
{ number: 967, english: "volume", spanish: "volumen", ipa: "/ˈvɒl yum, -yəm/" },
{ number: 968, english: "science", spanish: "ciencia", ipa: "/ˈsaɪ əns/" },
{ number: 969, english: "geography", spanish: "geografía", ipa: "/dʒiˈɒg rə fi/" },
{ number: 970, english: "article", spanish: "artículo", ipa: "/ˈɑr tɪ kəl/" },
{ number: 971, english: "weight", spanish: "peso", ipa: "/weɪt/" },
{ number: 972, english: "publication", spanish: "publicación", ipa: "/ˌpʌb lɪˈkeɪ ʃən/" },
{ number: 973, english: "line", spanish: "línea", ipa: "/laɪn/" },
{ number: 974, english: "technique", spanish: "técnica", ipa: "/tɛkˈnik/" },
{ number: 975, english: "dot", spanish: "punto", ipa: "/dɒt/" },
{ number: 976, english: "concept", spanish: "concepto", ipa: "/ˈkɒn sɛpt/" },
{ number: 977, english: "wealth", spanish: "riqueza", ipa: "/wɛlθ/" },
{ number: 978, english: "speech", spanish: "discurso", ipa: "/spitʃ/" },
{ number: 979, english: "strike", spanish: "huelga", ipa: "/straɪk/" },
{ number: 980, english: "debt", spanish: "deuda", ipa: "/dɛt/" },
{ number: 981, english: "economy", spanish: "economía", ipa: "/ɪˈkɒn ə mi/" },
{ number: 982, english: "security", spanish: "seguridad", ipa: "/sɪˈkyʊər ɪ ti/" },
{ number: 983, english: "president", spanish: "presidente", ipa: "/ˈprɛz ɪ dənt/" },
{ number: 984, english: "internet", spanish: "internet", ipa: "/ˈɪn tərˌnɛt/" },
{ number: 985, english: "network", spanish: "red", ipa: "/ˈnɛtˌwɜrk/" },
{ number: 986, english: "channel", spanish: "canal", ipa: "/ˈtʃæn l/" },
{ number: 987, english: "language", spanish: "idioma", ipa: "/ˈlæŋ gwɪdʒ/" },
{ number: 988, english: "text", spanish: "texto", ipa: "/tɛkst/" },
{ number: 989, english: "communication", spanish: "comunicación", ipa: "/kəˌmyu nɪˈkeɪ ʃən/" },
{ number: 990, english: "film", spanish: "película", ipa: "/fɪlm/" },
{ number: 991, english: "music", spanish: "música", ipa: "/ˈmyu zɪk/" },
{ number: 992, english: "poetry", spanish: "poesía", ipa: "/ˈpoʊ ɪ tri/" },
{ number: 993, english: "fashion", spanish: "moda", ipa: "/ˈfæʃ ən/" },
{ number: 994, english: "sound", spanish: "sonido", ipa: "/saʊnd/" },
{ number: 995, english: "collection", spanish: "colección", ipa: "/kəˈlɛk ʃən/" },
{ number: 996, english: "picture", spanish: "imagen", ipa: "/ˈpɪk tʃər/" },
{ number: 997, english: "contest", spanish: "concurso", ipa: "/ˈkɒn tɛst/" },
{ number: 998, english: "design", spanish: "diseño", ipa: "/dɪˈzaɪn/" },
{ number: 999, english: "issue", spanish: "problema", ipa: "/ˈɪʃ u/" },
{ number: 1000, english: "matter", spanish: "asunto", ipa: "/ˈmæt ər/" },
{ number: 1001, english: "union", spanish: "unión", ipa: "/ˈyun yən/" },
{ number: 1002, english: "success", spanish: "éxito", ipa: "/səkˈsɛs/" },
{ number: 1003, english: "wish", spanish: "deseo", ipa: "/wɪʃ/" },
{ number: 1004, english: "response", spanish: "respuesta", ipa: "/rɪˈspɒns/" },
{ number: 1005, english: "agreement", spanish: "acuerdo", ipa: "/əˈgri mənt/" },
{ number: 1006, english: "election", spanish: "elección", ipa: "/ɪˈlɛk ʃən/" },
{ number: 1007, english: "conflict", spanish: "conflicto", ipa: "/ˈkɒn flɪkt/" },
{ number: 1008, english: "advice", spanish: "consejo", ipa: "/ædˈvaɪs/" },
{ number: 1009, english: "blame", spanish: "culpa", ipa: "/bleɪm/" },
{ number: 1010, english: "threat", spanish: "amenaza", ipa: "/θrɛt/" },
{ number: 1011, english: "congress", spanish: "congreso", ipa: "/ˈkɒŋ grɪs/" },
{ number: 1012, english: "senator", spanish: "senador", ipa: "/ˈsɛn ə tər/" },
{ number: 1013, english: "decision", spanish: "decisión", ipa: "/dɪˈsɪʒ ən/" },
{ number: 1014, english: "weapon", spanish: "arma", ipa: "/ˈwɛp ən/" },
{ number: 1015, english: "vote", spanish: "voto", ipa: "/voʊt/" },
{ number: 1016, english: "navy", spanish: "marina de guerra", ipa: "/ˈneɪ vi/" },
{ number: 1017, english: "governor", spanish: "gobernador", ipa: "/ˈgʌv ər nər, ‐ə nər/" },
{ number: 1018, english: "legs", spanish: "piernas", ipa: "/lɛg/" },
{ number: 1019, english: "health", spanish: "salud", ipa: "/hɛlθ/" },
{ number: 1020, english: "body", spanish: "cuerpo", ipa: "/ˈbɒd i/" },
{ number: 1021, english: "treatment", spanish: "tratamiento", ipa: "/ˈtrit mənt/" },
{ number: 1022, english: "feet", spanish: "pies", ipa: "/fit/" },
{ number: 1023, english: "teeth", spanish: "dientes", ipa: "/tiθ/" },
{ number: 1024, english: "vision", spanish: "visión", ipa: "/ˈvɪʒ ən/" },
{ number: 1025, english: "condition", spanish: "condición", ipa: "/kənˈdɪʃ ən/" },
{ number: 1026, english: "dream", spanish: "sueña", ipa: "/drim/" },
{ number: 1027, english: "help", spanish: "ayuda", ipa: "/hɛlp/" },
{ number: 1028, english: "virus", spanish: "virus", ipa: "/ˈvaɪ rəs/" },
{ number: 1029, english: "information", spanish: "información", ipa: "/ˌɪn fərˈmeɪ ʃən/" },
{ number: 1030, english: "comment", spanish: "comentario", ipa: "/ˈkɒm ɛnt/" },
{ number: 1031, english: "story", spanish: "historia", ipa: "/ˈstɔr i, ˈstoʊr i/" },
{ number: 1032, english: "message", spanish: "mensaje", ipa: "/ˈmɛs ɪdʒ/" },
{ number: 1033, english: "access", spanish: "acceso", ipa: "/ˈæk sɛs/" },
{ number: 1034, english: "instrument", spanish: "instrumento", ipa: "/ˈɪn strə mənt/" },
{ number: 1035, english: "figure", spanish: "figura", ipa: "/ˈfɪg yər/" },
{ number: 1036, english: "dance", spanish: "baile", ipa: "/dæns, dɑns/" },
{ number: 1037, english: "style", spanish: "estilo", ipa: "/staɪl/" },
{ number: 1038, english: "art", spanish: "arte", ipa: "/ɑrt/" },
{ number: 1039, english: "concert", spanish: "concierto", ipa: "/ˈkɒn sɜrt, -sərt/" },
{ number: 1040, english: "match", spanish: "partido", ipa: "/mætʃ/" },
{ number: 1041, english: "stone", spanish: "piedra", ipa: "/stoʊn/" },
{ number: 1042, english: "universe", spanish: "universo", ipa: "/ˈyu nəˌvɜrs/" },
{ number: 1043, english: "competition", spanish: "competencia", ipa: "/ˌkɒm pɪˈtɪʃ ən/" },
{ number: 1044, english: "effort", spanish: "esfuerzo", ipa: "/ˈɛf ərt/" },
{ number: 1045, english: "aim", spanish: "objetivo", ipa: "/eɪm/" },
{ number: 1046, english: "introduction", spanish: "introducción", ipa: "/ˌɪn trəˈdʌk ʃən/" },
{ number: 1047, english: "act", spanish: "acto", ipa: "/ækt/" },
{ number: 1048, english: "value", spanish: "valor", ipa: "/ˈvæl yu/" },
{ number: 1049, english: "system", spanish: "sistema", ipa: "/ˈsɪs təm/" },
{ number: 1050, english: "chapter", spanish: "capítulo", ipa: "/ˈtʃæp tər/" },
{ number: 1051, english: "application", spanish: "solicitud", ipa: "/ˌæp lɪˈkeɪ ʃən/" },
{ number: 1052, english: "history", spanish: "historia", ipa: "/ˈhɪs tə ri, ˈhɪs tri/" },
{ number: 1053, english: "program", spanish: "programa", ipa: "/ˈproʊ græm, -grəm/" },
{ number: 1054, english: "guide", spanish: "guía", ipa: "/gaɪd/" },
{ number: 1055, english: "people", spanish: "gente", ipa: "/ˈpi pəl/" },
{ number: 1056, english: "citizen", spanish: "ciudadano", ipa: "/ˈsɪt ə zən, -sən/" },
{ number: 1057, english: "youth", spanish: "juventud", ipa: "/yuθ/" },
{ number: 1058, english: "culture", spanish: "cultura", ipa: "/ˈkʌl tʃər/" },
{ number: 1059, english: "victim", spanish: "víctima", ipa: "/ˈvɪk tɪm/" },
{ number: 1060, english: "foundation", spanish: "fundación", ipa: "/faʊnˈdeɪ ʃən/" },
{ number: 1061, english: "committee", spanish: "comité", ipa: "/kəˈmɪt i/" },
{ number: 1062, english: "enemy", spanish: "enemigo", ipa: "/ˈɛn ə mi/" },
{ number: 1063, english: "population", spanish: "población", ipa: "/ˌpɒp yəˈleɪ ʃən/" },
{ number: 1064, english: "front", spanish: "frente", ipa: "/frʌnt/" },
{ number: 1065, english: "cinema", spanish: "cine", ipa: "/ˈsɪn ə mə/" },
{ number: 1066, english: "magazine", spanish: "revista", ipa: "/ˌmæg əˈzin, ˈmæg əˌzin/" },
{ number: 1067, english: "thing", spanish: "cosa", ipa: "/θɪŋ/" },
{ number: 1068, english: "marriage", spanish: "matrimonio", ipa: "/ˈmær ɪdʒ/" },
{ number: 1069, english: "nature", spanish: "naturaleza", ipa: "/ˈneɪ tʃər/" },
{ number: 1070, english: "actress", spanish: "actriz", ipa: "/ˈæk trɪs/" },
{ number: 1071, english: "movie", spanish: "película", ipa: "/ˈmu vi/" },
{ number: 1072, english: "theater", spanish: "teatro", ipa: "/ˈθi ə tər, ˈθiə-/" },
{ number: 1073, english: "lecture", spanish: "conferencia", ipa: "/ˈlɛk tʃər/" },
{ number: 1074, english: "objective", spanish: "objetivo", ipa: "/əbˈdʒɛk tɪv/" },
{ number: 1075, english: "practice", spanish: "práctica", ipa: "/ˈpræk tɪs/" },
{ number: 1076, english: "education", spanish: "educación", ipa: "/ˌɛdʒ ʊˈkeɪ ʃən/" },
{ number: 1077, english: "page", spanish: "página", ipa: "/peɪdʒ/" },
{ number: 1078, english: "section", spanish: "sección", ipa: "/ˈsɛk ʃən/" },
{ number: 1079, english: "study", spanish: "estudio", ipa: "/ˈstʌd i/" },
{ number: 1080, english: "avenue", spanish: "avenida", ipa: "/ˈæv əˌnyu, -ˌnu/" },
{ number: 1082, english: "site", spanish: "sitio", ipa: "/saɪt/" },
{ number: 1083, english: "zone", spanish: "zona", ipa: "/zoʊn/" },
{ number: 1084, english: "powder", spanish: "polvo", ipa: "/ˈpaʊ dər/" },
{ number: 1085, english: "visit", spanish: "visita", ipa: "/ˈvɪz ɪt/" },
{ number: 1087, english: "south", spanish: "sur", ipa: "/saʊθ/" },
{ number: 1088, english: "motor", spanish: "motor", ipa: "/ˈmoʊ tər/" },
{ number: 1089, english: "novel", spanish: "novela", ipa: "/ˈnɒv əl/" },
{ number: 1090, english: "string", spanish: "cuerda", ipa: "/strɪŋ/" },
{ number: 1091, english: "space", spanish: "espacio", ipa: "/speɪs/" },
{ number: 1092, english: "signal", spanish: "señal", ipa: "/ˈsɪg nl/" },
{ number: 1093, english: "couple", spanish: "par", ipa: "/ˈkʌp əl/" },
{ number: 1094, english: "individual", spanish: "individual", ipa: "/ˌɪn dəˈvɪdʒ u əl/" },
{ number: 1097, english: "village", spanish: "pueblo", ipa: "/ˈvɪl ɪdʒ/" },
{ number: 1095, english: "baby", spanish: "bebé", ipa: "/ˈbeɪ bi/" },
{ number: 1096, english: "public", spanish: "público", ipa: "/ˈpʌb lɪk/" },
{ number: 1099, english: "basket", spanish: "cesta", ipa: "/ˈbæs kɪt, ˈbɑ skɪt/" },
{ number: 1100, english: "staff", spanish: "personal", ipa: "/stæf, stɑf/" },
{ number: 1102, english: "evidence", spanish: "evidencia", ipa: "/ˈɛv ɪ dəns/" },
{ number: 1103, english: "alcohol", spanish: "alcohol", ipa: "/ˈæl kəˌhɔl, -ˌhɒl/" },
{ number: 1104, english: "athlete", spanish: "atleta", ipa: "/ˈæθ lit/" },
{ number: 1105, english: "gym", spanish: "gimnasio", ipa: "/dʒɪm/" },
{ number: 1106, english: "coach", spanish: "entrenador", ipa: "/koʊtʃ/" },
{ number: 1107, english: "point", spanish: "punto", ipa: "/pɔɪnt/" },
{ number: 1098, english: "mirror", spanish: "espejo", ipa: "/ˈmɪr ər/" },
{ number: 1108, english: "basketball", spanish: "baloncesto", ipa: "/ˈbæs kɪtˌbɔl, ˈbɑ skɪt-/" },
{ number: 1109, english: "player", spanish: "jugador", ipa: "/ˈpleɪ ər/" },
{ number: 1111, english: "sport", spanish: "deporte", ipa: "/spɔrt, spoʊrt/" },
{ number: 1112, english: "leave", spanish: "salida", ipa: "/liv/" },
{ number: 1101, english: "charge", spanish: "carga", ipa: "/tʃɑrdʒ/" },
{ number: 1113, english: "climate", spanish: "clima", ipa: "/ˈklaɪ mɪt/" },
{ number: 1086, english: "transportation", spanish: "transporte", ipa: "/ˌtræns pərˈteɪ ʃən/" },
{ number: 1115, english: "weather", spanish: "clima", ipa: "/ˈwɛð ər/" },
{ number: 1114, english: "soil", spanish: "suelo", ipa: "/sɔɪl/" },
{ number: 1116, english: "memory", spanish: "memoria", ipa: "/ˈmɛm ə ri/" },
{ number: 1117, english: "entrance", spanish: "entrada", ipa: "/ˈɛn trəns/" },
{ number: 1119, english: "airehonor", spanish: "airehonor", ipa: "/ˈɒn ər/" },
{ number: 1118, english: "attitude", spanish: "actitud", ipa: "/ˈæt ɪˌtud, -ˌtyud/" },
{ number: 1122, english: "favor", spanish: "favor", ipa: "/ˈfeɪ vər/" },
{ number: 1123, english: "trend", spanish: "tendencia", ipa: "/trɛnd/" },
{ number: 1125, english: "surprise", spanish: "sorpresa", ipa: "/sərˈpraɪz, sə-/" },
{ number: 1110, english: "step", spanish: "paso", ipa: "/stɛp/" },
{ number: 1124, english: "phrase", spanish: "frase", ipa: "/freɪz/" },
{ number: 1127, english: "conversation", spanish: "conversación", ipa: "/ˌkɒn vərˈseɪ ʃən/" },
{ number: 1129, english: "consequence", spanish: "consecuencia", ipa: "/ˈkɒn sɪˌkwɛns/" },
{ number: 1128, english: "desire", spanish: "deseo", ipa: "/dɪˈzaɪər/" },
{ number: 1120, english: "mistake", spanish: "error", ipa: "/mɪˈsteɪk/" },
{ number: 1130, english: "pleasure", spanish: "placer", ipa: "/ˈplɛʒ ər/" },
{ number: 1131, english: "existence", spanish: "existencia", ipa: "/ɪgˈzɪs təns/" },
{ number: 1132, english: "responsibility", spanish: "responsabilidad", ipa: "/rɪˌspɒn səˈbɪl ɪ ti/" },
{ number: 1133, english: "doubt", spanish: "duda", ipa: "/daʊt/" },
{ number: 1121, english: "joy", spanish: "alegría", ipa: "/dʒɔɪ/" },
{ number: 1134, english: "humor", spanish: "humor", ipa: "/ˈhyu mər/" },
{ number: 1135, english: "permit", spanish: "permiso", ipa: "/ˈpɜr mɪt/" },
{ number: 1126, english: "fault", spanish: "culpa", ipa: "/fɔlt/" },
{ number: 1081, english: "community", spanish: "comunidad", ipa: "/kəˈmyu nɪ ti/" },
{ number: 1138, english: "symbols", spanish: "símbolos", ipa: "/ˈsɪm bəl/" },
{ number: 1136, english: "position", spanish: "posición", ipa: "/pəˈzɪʃ ən/" },
{ number: 1142, english: "attempt", spanish: "intento", ipa: "/əˈtɛmpt/" },
{ number: 1141, english: "direction", spanish: "dirección", ipa: "/dɪˈrɛk ʃən, ˈdaɪ-/" },
{ number: 1144, english: "character", spanish: "personaje", ipa: "/ˈkær ɪk tər/" },
{ number: 1143, english: "behavior", spanish: "comportamiento", ipa: "/bɪˈheɪv yər/" },
{ number: 1145, english: "damage", spanish: "daño", ipa: "/ˈdæm ɪdʒ/" },
{ number: 1146, english: "origin", spanish: "origen", ipa: "/ˈɔr ɪ dʒɪn, ˈɒr-/" },
{ number: 1147, english: "reality", spanish: "realidad", ipa: "/riˈæl ɪ ti/" },
{ number: 1137, english: "experience", spanish: "experiencia", ipa: "/ɪkˈspɪər i əns/" },
{ number: 1149, english: "truth", spanish: "verdad", ipa: "/truθ/" },
{ number: 1148, english: "failure", spanish: "fracaso", ipa: "/ˈfeɪl yər/" },
{ number: 1152, english: "permission", spanish: "permiso", ipa: "/pərˈmɪʃ ən/" },
{ number: 1153, english: "situation", spanish: "situación", ipa: "/ˌsɪtʃ uˈeɪ ʃən/" },
{ number: 1151, english: "load", spanish: "carga", ipa: "/loʊd/" },
{ number: 1154, english: "benefit", spanish: "beneficio", ipa: "/ˈbɛn ə fɪt/" },
{ number: 1156, english: "attention", spanish: "atención", ipa: "/əˈtɛn ʃən/" },
{ number: 1157, english: "respect", spanish: "el respeto", ipa: "/rɪˈspɛkt/" },
{ number: 1158, english: "religion", spanish: "religión", ipa: "/rɪˈlɪdʒ ən/" },
{ number: 1159, english: "amount", spanish: "cantidad", ipa: "/əˈmaʊnt/" },
{ number: 1160, english: "alternative", spanish: "alternativa", ipa: "/ɔlˈtɜr nə tɪv, æl-/" },
{ number: 1155, english: "title", spanish: "título", ipa: "/ˈtaɪt l/" },
{ number: 1161, english: "kind", spanish: "tipo", ipa: "/kaɪnd/" },
{ number: 1163, english: "award", spanish: "premio", ipa: "/əˈwɔrd/" },
{ number: 1164, english: "purpose", spanish: "propósito", ipa: "/ˈpɜr pəs/" },
{ number: 1165, english: "role", spanish: "papel", ipa: "/roʊl/" },
{ number: 1167, english: "choice", spanish: "elección", ipa: "/tʃɔɪs/" },
{ number: 1150, english: "live", spanish: "vida", ipa: "/lɪv/" },
{ number: 1166, english: "voice", spanish: "voz", ipa: "/vɔɪs/" },
{ number: 1168, english: "difficulty", spanish: "dificultad", ipa: "/ˈdɪf ɪˌkʌl ti, -kəl ti/" },
{ number: 1169, english: "explanation", spanish: "explicación", ipa: "/ˌɛk spləˈneɪ ʃən/" },
{ number: 1170, english: "region", spanish: "región", ipa: "/ˈri dʒən/" },
{ number: 1140, english: "signature", spanish: "firma", ipa: "/ˈsɪg nə tʃər, -ˌtʃʊər/" },
{ number: 1171, english: "ground", spanish: "suelo", ipa: "/graʊnd/" },
{ number: 1174, english: "department", spanish: "departamento", ipa: "/dɪˈpɑrt mənt/" },
{ number: 1175, english: "piece", spanish: "pieza", ipa: "/pis/" },
{ number: 1172, english: "yard", spanish: "yarda, patio", ipa: "/yɑrd/" },
{ number: 1176, english: "market", spanish: "mercado", ipa: "/ˈmɑr kɪt/" },
{ number: 1179, english: "question", spanish: "pregunta", ipa: "/ˈkwɛs tʃən/" },
{ number: 1177, english: "artist", spanish: "artista", ipa: "/ˈɑr tɪst/" },
{ number: 1178, english: "sibling", spanish: "hermano", ipa: "/ˈsɪb lɪŋ/" },
{ number: 1181, english: "change", spanish: "cambio", ipa: "/tʃeɪndʒ/" },
{ number: 1180, english: "address", spanish: "dirección", ipa: "/əˈdrɛs, ˈæd rɛs/" },
{ number: 1184, english: "entry", spanish: "entrada", ipa: "/ˈɛn tri/" },
{ number: 1182, english: "review", spanish: "revisión", ipa: "/rɪˈvyu/" },
{ number: 1183, english: "majority", spanish: "mayoría", ipa: "/məˈdʒɔr ɪ ti, -ˈdʒɒr-/" },
{ number: 1185, english: "effect", spanish: "efecto", ipa: "/ɪˈfɛkt/" },
{ number: 1162, english: "subject", spanish: "tema", ipa: "/ˈsʌb dʒɪkt/" },
{ number: 1186, english: "opportunity", spanish: "oportunidad", ipa: "/ˌɒp ərˈtu nɪ ti, -ˈtyu-/" },
{ number: 1187, english: "hope", spanish: "esperanza", ipa: "/hoʊp/" },
{ number: 1190, english: "construction", spanish: "construcción", ipa: "/kənˈstrʌk ʃən/" },
{ number: 1189, english: "turn", spanish: "giro", ipa: "/tɜrn/" },
{ number: 1139, english: "scene", spanish: "escena", ipa: "/sin/" },
{ number: 1191, english: "protection", spanish: "protección", ipa: "/prəˈtɛk ʃən/" },
{ number: 1173, english: "object", spanish: "objeto", ipa: "/ˈɒb dʒɪkt, -dʒɛkt/" },
{ number: 1192, english: "production", spanish: "producción", ipa: "/prəˈdʌk ʃən/" },
{ number: 1197, english: "problem", spanish: "problema", ipa: "/ˈprɒb ləm/" },
{ number: 1193, english: "solution", spanish: "solución", ipa: "/səˈlu ʃən/" },
{ number: 1198, english: "activity", spanish: "actividad", ipa: "/ækˈtɪv ɪ ti/" },
{ number: 1199, english: "content", spanish: "contenido", ipa: "/ˈkɒn tɛnt/" },
{ number: 1200, english: "equipment", spanish: "equipo", ipa: "/ɪˈkwɪp mənt/" },
{ number: 1196, english: "option", spanish: "opción", ipa: "/ˈɒp ʃən/" },
{ number: 1201, english: "category", spanish: "categoría", ipa: "/ˈkæt ɪˌgɔr i, -ˌgoʊr i/" },
{ number: 1202, english: "description", spanish: "descripción", ipa: "/dɪˈskrɪp ʃən/" },
{ number: 1203, english: "image", spanish: "imagen", ipa: "/ˈɪm ɪdʒ/" },
{ number: 1194, english: "result", spanish: "resultado", ipa: "/rɪˈzʌlt/" },
{ number: 1205, english: "account", spanish: "cuenta", ipa: "/əˈkaʊnt/" },
{ number: 1195, english: "results", spanish: "resultados", ipa: "/rɪˈzʌlt/" },
{ number: 1207, english: "control", spanish: "control", ipa: "/kənˈtroʊl/" },
{ number: 1206, english: "profile", spanish: "perfil", ipa: "/ˈproʊ faɪl/" },
{ number: 1212, english: "version", spanish: "versión", ipa: "/ˈvɜr ʒən, -ʃən/" },
{ number: 1210, english: "case", spanish: "caso", ipa: "/keɪs/" },
{ number: 1188, english: "mind", spanish: "mente", ipa: "/maɪnd/" },
{ number: 1204, english: "call", spanish: "llamada", ipa: "/kɔl/" },
{ number: 1208, english: "member", spanish: "miembro", ipa: "/ˈmɛm bər/" },
{ number: 1215, english: "service", spanish: "servicio", ipa: "/ˈsɜr vɪs/" },
{ number: 1211, english: "order", spanish: "orden", ipa: "/ˈɔr dər/" },
{ number: 1213, english: "view", spanish: "vista", ipa: "/vyu/" },
{ number: 1214, english: "part", spanish: "parte", ipa: "/pɑrt/" },
{ number: 1217, english: "number", spanish: "número", ipa: "/ˈnʌm bər/" },
{ number: 1218, english: "departure", spanish: "salida", ipa: "/dɪˈpɑr tʃər/" },
{ number: 1219, english: "journey", spanish: "viaje", ipa: "/ˈdʒɜr ni/" },
{ number: 1221, english: "bridge", spanish: "puente", ipa: "/brɪdʒ/" },
{ number: 1220, english: "tourist", spanish: "turista", ipa: "/ˈtʊər ɪst/" },
{ number: 1225, english: "tent", spanish: "tienda", ipa: "/tɛnt/" },
{ number: 1222, english: "adventure", spanish: "aventuras", ipa: "/ædˈvɛn tʃər/" },
{ number: 1209, english: "group", spanish: "grupo", ipa: "/grup/" },
{ number: 1223, english: "vehicle", spanish: "vehículo", ipa: "/ˈvi ɪ kəl/" },
{ number: 1227, english: "guy", spanish: "chico", ipa: "/gaɪ/" },
{ number: 1228, english: "luggage", spanish: "equipaje", ipa: "/ˈlʌg ɪdʒ/" },
{ number: 1230, english: "alien", spanish: "extraterrestre", ipa: "/ˈeɪl yən, ˈeɪ li ən/" },
{ number: 1226, english: "flu", spanish: "gripe", ipa: "/flu/" },
{ number: 1229, english: "cotton", spanish: "algodón", ipa: "/ˈkɒt n/" },
{ number: 1232, english: "speaker", spanish: "altavoz", ipa: "/ˈspi kər/" },
{ number: 1231, english: "bookmark", spanish: "marcador", ipa: "/ˈbʊkˌmɑrk/" },
{ number: 1233, english: "pickpocket", spanish: "roba carteras", ipa: "/ˈpɪkˌpɒk ɪt/" },
{ number: 1236, english: "air", spanish: "aire", ipa: "/ɛər/" },
{ number: 1235, english: "wind", spanish: "viento", ipa: "/wɪnd/" },
{ number: 1237, english: "lyric", spanish: "lírica", ipa: "/ˈlɪr ɪk/" },
{ number: 1238, english: "taste", spanish: "gusto", ipa: "/teɪst/" },
{ number: 1240, english: "crowd", spanish: "multitud", ipa: "/kraʊd/" },
{ number: 1239, english: "darling", spanish: "cariño", ipa: "/ˈdɑr lɪŋ/" },
{ number: 1243, english: "tear", spanish: "lágrima", ipa: "/tɪər/" },
{ number: 1224, english: "motorcycle", spanish: "motocicleta", ipa: "/ˈmoʊ tərˌsaɪ kəl/" },
{ number: 1245, english: "routine", spanish: "rutina", ipa: "/ruˈtin/" },
{ number: 1247, english: "prey", spanish: "presa", ipa: "/preɪ/" },
{ number: 1246, english: "drawing", spanish: "dibujo", ipa: "/ˈdrɔ ɪŋ/" },
{ number: 1248, english: "digestion", spanish: "digestión", ipa: "/dɪˈdʒɛs tʃən, daɪ-/" },
{ number: 1249, english: "glance", spanish: "vistazo", ipa: "/glæns, glɑns/" },
{ number: 1250, english: "concern", spanish: "preocupación", ipa: "/kənˈsɜrn/" },
{ number: 1251, english: "ocean", spanish: "océano", ipa: "/ˈoʊ ʃən/" },
{ number: 1242, english: "plan", spanish: "plan", ipa: "/plæn/" },
{ number: 1244, english: "pain", spanish: "dolor", ipa: "/peɪn/" },
{ number: 1252, english: "amazement", spanish: "asombro", ipa: "/əˈmeɪz mənt/" },
{ number: 1255, english: "gleam", spanish: "destello", ipa: "/glim/" },
{ number: 1254, english: "portrait", spanish: "retrato", ipa: "/ˈpɔr trɪt, -treɪt, ˈpoʊr-/" },
{ number: 1253, english: "blink", spanish: "parpadeo", ipa: "/blɪŋk/" },
{ number: 1258, english: "telescope", spanish: "telescopio", ipa: "/ˈtɛl əˌskoʊp/" },
{ number: 1257, english: "importance", spanish: "importancia", ipa: "/ɪmˈpɔr tns/" },
{ number: 1256, english: "fact", spanish: "hecho", ipa: "/fækt/" },
{ number: 1261, english: "proof", spanish: "prueba", ipa: "/pruf/" },
{ number: 1262, english: "shoulder", spanish: "hombro", ipa: "/ˈʃoʊl dər/" },
{ number: 1263, english: "forbearance", spanish: "paciencia", ipa: "/fɔrˈbɛər əns/" },
{ number: 1264, english: "indifference", spanish: "indiferencia", ipa: "/ɪnˈdɪf ər əns/" },
{ number: 1265, english: "grief", spanish: "dolor", ipa: "/grif/" },
{ number: 1266, english: "bodyguard", spanish: "guardaespaldas", ipa: "/ˈbɒd iˌgɑrd/" },
{ number: 1267, english: "release", spanish: "lanzamiento", ipa: "/rɪˈlis/" },
{ number: 1268, english: "appearance", spanish: "apariencia", ipa: "/əˈpɪər əns/" },
{ number: 1269, english: "development", spanish: "desarrollo", ipa: "/dɪˈvɛl əp mənt/" },
{ number: 1270, english: "functionality", spanish: "funcionalidad", ipa: "/ˈfʌŋk ʃə nl/" },
{ number: 1271, english: "hangar", spanish: "hangar", ipa: "/ˈhæŋ ər/" },
{ number: 1216, english: "sum", spanish: "suma", ipa: "/sʌm/" },
{ number: 1241, english: "soul", spanish: "alma", ipa: "/soʊl/" },
{ number: 1260, english: "dove", spanish: "paloma", ipa: "/dʌv/" },
{ number: 1274, english: "offer", spanish: "oferta", ipa: "/ˈɔ fər, ˈɒf ər/" },
{ number: 1275, english: "payment", spanish: "pago", ipa: "/ˈpeɪ mənt/" },
{ number: 1276, english: "server", spanish: "servidor", ipa: "/ˈsɜr vər/" },
{ number: 1272, english: "carnival", spanish: "carnaval", ipa: "/ˈkɑr nə vəl/" },
{ number: 1273, english: "feature", spanish: "característica", ipa: "/ˈfi tʃər/" },
{ number: 1277, english: "partner", spanish: "compañero", ipa: "/ˈpɑrt nər/" },
{ number: 1234, english: "hut", spanish: "choza", ipa: "/hʌt/" },
{ number: 1280, english: "crockery", spanish: "vajilla", ipa: "/ˈkrɒk ə ri/" },
{ number: 1283, english: "hob", spanish: "hornilla (cocina)", ipa: "/hɒb/" },
{ number: 1282, english: "toaster", spanish: "tostadora", ipa: "/ˈtoʊ stər/ " },
{ number: 1278, english: "cradle", spanish: "cuna", ipa: "/ˈkreɪd l/" },
{ number: 1279, english: "sleeve", spanish: "manga", ipa: "/sliv/" },
{ number: 1281, english: "microwave", spanish: "microondas", ipa: "/ˈmaɪ kroʊˌweɪv/" },
{ number: 1259, english: "report", spanish: "informe", ipa: "/rɪˈpɔrt, -ˈpoʊrt/" }];