module.exports = ["/ˈmɑr vəl/",
"/bɔrd, boʊrd/",
"/liʃ/",
"/ɪˈlɛk trɪ kəl ˈaʊt lɛt, -lɪt/",
"/ˈsʌnˌglæs ɪz, -ˌglɑ sɪz/",
"/ˈskruˌdraɪ vər/",
"/tri/",
"/ˈæs trəˌnɔt, -ˌnɒt/",
"/stim/",
"/strit/",
"/ˈpɜr fyum/",
"/soʊp/",
"/ˈblæŋ kɪt/",
"/ˈklæsˌrum/",
"/ˈlɒl iˌpɒp/",
"/skʌŋk/",
"/ˈteɪ bəlˌklɔθ/",
"/'sʌb məˈrin/",
"/ˈhæŋ kər tʃɪf/",
"/ˈkæmpˌfaɪər/",
"/ˈwʊdˌpɛk ər/",
"/ˈsaɪdˌwɔk/",
"/ˈkrɔsˌwɔk, ˈkrɒs-/",
"/flæg/",
"/ˈsɛp tər/",
"/ɪər/",
"/bəˈreɪ/",
"/ˈkɒl əm/",
"/tul/",
"/frut/",
"/bʌs/",
"/ˈdɪk ʃəˌnɛr i/",
"/pɪn/",
"/ˈbɪl dɪŋ/",
"/kəmˈpyu tər/",
"/ˈti tʃər/",
"/wik/",
"/ˈkɔl drən/",
"/kəˈmi li ən/",
"/ˈaɪs bɜrg/",
"/ˌkæŋ gəˈru/",
"/ˈsnoʊˌmæn/",
"/feɪs/",
"/ˈkreɪ ɒn, -ən/",
"/ˈpi lər/",
"/ˈmeɪlˌmæn/",
"/boʊt/",
"/bæt/",
"/koʊm/",
"/ˈaɪ lənd/",
"/ˈsɪt i/",
"/ˈbækˌpæk/",
"/leɪs/",
"/səˈrɪndʒ, ˈsɪr ɪndʒ/",
"/ˈkæn dlˌstɪk/",
"/kreɪt/",
"/ˈkæt l/",
"/ˈbʊkˌstɔr, -ˌstoʊr/",
"/hʊd/",
"/kɔrd/",
"/ˈtʃɛr i/",
"/ˈrɪb ən/",
"/bɛər/",
"/ˈbæn dɪdʒ/",
"/ˈbæt ə ri/",
"/wɜrm/",
"/ˈkɑr pən tər/",
"/pɑrk/",
"/ˈgɑr bɪdʒ/",
"/ˈræk ɪt/",
"/ˈɛks kəˌveɪ tər/",
"/ˈɑr mər/",
"/ˈeɪn dʒəl/",
"/'si hɔrs/",
"/kɑrd/",
"/smaɪl/",
"/ˈstʌm ək/",
"/koʊt/",
"/ˈkæk təs/",
"/pætʃ/",
"/ˈbʌk ɪt/",
"/roʊz/",
"/ˈkloʊzˌpɪn/",
"/ˈmɛd l/",
"/ˈɔr tʃərd/",
"/ˈkæm ər ə, ˈkæm rə/",
"/ɑrm/",
"/ˈmɜrˌmeɪd/",
"/ˈɛn dʒən/",
"/bɛntʃ/",
"/glæs, glɑs/",
"/ˈʌv ən/",
"/ˈspaɪ dər/",
"/ˈɪərˌrɪŋ, -ɪŋ/",
"/ˈʰwɪs əl, ˈwɪs-/",
"/pəˈdʒɑ mə, -ˈdʒæm ə/",
"/ˈi gəl/",
"/ˈlɒb stər/",
"/ˈlɛm ən/",
"/ˈʃæd oʊ/",
"/ˈpɪn sərz/",
"/tʃɜrtʃ/",
"/aɪ/",
"/ˈæt ɪk/",
"/stɔrm/",
"/bɔɪ/",
"/ˈvæk yum, -yu əm/",
"/ˈlaɪfˌgɑrd/",
"/ˈkæb ɪdʒ/",
"/ˈstrɔˌbɛr i, -bə ri/",
"/ˈlɒk ər/",
"/ˈpʌd l/",
"/grum, grʊm/",
"/ˈræzˌbɛr i/",
"/ˈræb ɪt/",
"/snoʊ/",
"/ˈheɪ zəlˌnʌt/",
"/kreɪn/",
"/fæn/",
"/ˈɑrmˌtʃɛər/",
"/hɛər/",
"/ˈdɒŋ ki, ˈdɔŋ-, ˈdʌŋ-/",
"/hæt/",
"/kæf, kɑf/",
"/ʌmˈbrɛl ə/",
"/ˈaɪˌbraʊ/",
"/ˈgrænˌfɑ ðər, ˈgrænd-/",
"/ˈwɛd ɪŋ/",
"/ˈseɪ lər/",
"/ˈskeɪtˌbɔrd, -ˌboʊrd/",
"/bɪərd/",
"/ˈrɪv ər/",
"/ˈdæn dlˌaɪ ən/",
"/ˈpɛn səl/",
"/ˈfʌn l/",
"/dreɪn/",
"/ˈpeɪn tər/",
"/kaʊ/",
"/ˈtʃɪl i ˈpɛp ər/",
"/ˈlaɪtˌhaʊs/",
"/θrɛd/",
"/θərˈmɒm ɪ tər/",
"/ˈpæd l/",
"/mæn/",
"/ˈhɛl mɪt/",
"/ˈfɔr ɪd/",
"/ˈhɒs pɪ tl/",
"/ˈgʌt ər/",
"/ˈeɪ kɔrn, ˈeɪ kərn/",
"/ˈbɛg ər/",
"/ˈeɪ prən/",
"/wɛl/",
"/ˈpæl ɪs/",
"/ˈtʃɒpˌstɪks/",
"/lɔn/",
"/ˈdaɪ mənd, ˈdaɪ ə-/",
"/ˈpoʊ ni/",
"/ræt/",
"/ˈwɒl ɪt, ˈwɔ lɪt/",
"/seɪf/",
"/veɪs, veɪz, vɑz/",
"/fɔrk/",
"/pəˈlis mən/",
"/ˈhɛl ɪˌkɒp tər, ˈhi lɪ-/",
"/ˈrʌn ər/",
"/ˈkær ɪdʒ/",
"/ˈbʊtʃ ər ʃɒp/",
"/ˈmæ trɪs/",
"/freɪm/",
"/ˈdɪʃˌwɒʃ ər, -ˌwɔ ʃər/",
"/ˈsɪz ərz/",
"/ˈsoʊ fə/",
"/ˈsi lɪŋ/",
"/ˈkɔrkˌskru/",
"/ˈkɑr pɪt/",
"/paɪp/",
"/seɪl/",
"/ˈlɪz ərd/",
"/swɪŋ/",
"/prəˈdʒɛk tər/",
"/ˈɑr tʃər/",
"/si/",
"/skɜrt/",
"/prist/",
"/fʊt/",
"/ˈhæm ər/",
"/ˈpʌp i/",
"/speɪd/",
"/ˈgreɪ tər/",
"/draʊt/",
"/ˈsɛl ər/",
"/ˈwɔ tərˌmɛl ən/",
"/ˈsɪŋ ər/",
"/ɜrθ/",
"/ˈswɪmˌsut/",
"/mʌg/",
"/ˈpɑr sli/",
"/dʒus/",
"/sɪŋk/",
"/wɪtʃ/",
"/ˈmʌʃ rum, -rʊm/",
"/ˈmaʊn tn/",
"/ˈnʌtˌkræk ər/",
"/drɪl/",
"/ˈsiˌsɔ/",
"/ˈblækˌsmɪθ/",
"/ˈhɛdʒˌhɒg, -ˌhɔg/",
"/kræb/",
"/bit/",
"/ˈsiˌwid/",
"/slaɪd/",
"/ʃild/",
"/ˈdʒæk ɪt/",
"/ˈpaɪ rət/",
"/səˈspɛn dər/",
"/spaɪn/",
"/taɪ/",
"/dɑrk/",
"/pleɪt, plæt/",
"/ˈsli pɪŋ bæg/",
"/ˈvɛdʒ tə bəl/",
"/ˈθʌmˌtæk/",
"/bəˈnɒk yə lər, baɪ-/",
"/vɒlˈkeɪ noʊ/",
"/nɜrs/",
"/geɪt/",
"/ˈwɔ tər, ˈwɒt ər/",
"/dwɔrf/",
"/ˈzɪp ər/",
"/slit/",
"/ˈbʌt ək/",
"/bʊk/",
"/ˈpeɪ pər/",
"/keɪv/",
"/ˈwɛərˌwʊlf/",
"/ˈpɒk ɪt/",
"/kaɪt/",
"/ˈtuθˌbrʌʃ/",
"/ʃip/",
"/pu/",
"/stɔrk/",
"/ti/",
"/lɔg, lɒg/",
"/ˈɛərˌpleɪn/",
"/sprɪŋ/",
"/ˈbæθˌroʊb, ˈbɑθ-/",
"/ˈtɜr ki/",
"/ˈtɛn ɪs/",
"/ˈfɛð ər/",
"/ˈwɪndˌmɪl/",
"/ˈleɪ diˌbʌg/",
"/faɪər/",
"/trʌŋk/",
"/ˌrɛf əˈri/",
"/kraʊn/",
"/ˈdʒu əl ri/",
"/ˈbæθˌtʌb, ˈbɑθ-/",
"/ˈwɔl rəs, ˈwɒl-/",
"/hɛn/",
"/gloʊb/",
"/ˈwɪn doʊˌsɪl/",
"/ˈplʌn dʒər/",
"/ˈstɪər ɪŋ ʰwil, wil/",
"/ʃɜrt/",
"/ˈæntˌi tər/",
"/kyub/",
"/nʌt/",
"/ˈblækˌbɔrd, -ˌboʊrd/",
"/ˈpaɪ lət/",
"/ˈtʌn l/",
"/ɑrtʃ/",
"/klit/",
"/ˈθɪm bəl/",
"/ˈkɒbˌwɛb/",
"/ˈgrænˌmʌð ər/",
"/sneɪl/",
"/ˈbɛdˌrum, -ˌrʊm/",
"/læm/",
"/breɪn/",
"/klɔ/",
"/ˈhændˌkʌf/",
"/brɛd/",
"/tæˈtu/",
"/ˈpɛt l/",
"/ˈprɪn sɪs, -sɛs, prɪnˈsɛs/",
"/ˈkoʊ kəˌnʌt, -nət/",
"/fɔl/",
"/læk/",
"/bʌlb/",
"/gus/",
"/ˈdʒɛs tər/",
"/bʌn/",
"/sleɪv/",
"/hil/",
"/stul/",
"/ˈtʃɪm ni/",
"/meɪz/",
"/veɪl/",
"/ˈkʌb ərd/",
"/nɒt/",
"/brum, brʊm/",
"/ˈsteɪ plər/",
"/reɪk/",
"/ˈdʌstˌpæn/",
"/ˈstreɪ nər/",
"/ˈkæt əˌpɪl ər, ˈkæt ər-/",
"/dʒʌg/",
"/wɪg/",
"/θʌm/",
"/rɪˈsit/",
"/tʃik/",
"/flaʊər, ˈflaʊ ər/",
"/ʰweɪl, weɪl/",
"/tʃɛst/",
"/kæp/",
"/ˈɛn vəˌloʊp, ˈɑn-/",
"/blaɪnd/",
"/ˈsɔ sɪdʒ/",
"/ˈgɑr lɪk/",
"/sɒk/",
"/bəˈlun/",
"/treɪ/",
"/greɪp/",
"/ˈɔ strɪtʃ, ˈɒs trɪtʃ/",
"/ˈdʒɪgˌsɔ/",
"/fɪst/",
"/wɒsp/",
"/ˈpiˌkɒk/",
"/brɪk/",
"/θroʊt/",
"/frɪdʒ/",
"/ˈspæn ər/",
"/ˈstrɛtʃ ər/",
"/flʌd/",
"/ˈpʌp ɪt/",
"/blaʊs, blaʊz/",
"/fɪn/",
"/ˈnid l/",
"/pɒt/",
"/θaɪ/",
"/mʌd/",
"/ˈɛs kəˌleɪ tər/",
"/træp/",
"/ˈpær ət/",
"/taɪər/",
"/ˌæv əˈkɑ doʊ, ˌɑ və-/",
"/ˈkiˌhoʊl/",
"/ˈkær ət/",
"/ˈbitˌrut, -ˌrʊt/",
"/gɪər/",
"/lʌŋ/",
"/ˈskwɜr əl/",
"/drɒp/",
"/ˈroʊ lər/",
"/wɪŋ/",
"/pɛər/",
"/moʊl/",
"/bik/",
"/ˈpʌmp kɪn/",
"/skru/",
"/ˈwæg ən/",
"/ˈkʌt lə ri/",
"/nʌn/",
"/aʊl/",
"/ˈsnoʊˌfleɪk/",
"/waɪər/",
"/ˈteɪ lər/",
"/ˈbɛl i/",
"/ˈyu nəˌfɔrm/",
"/nɛk/",
"/ˈslɪp ər/",
"/sut/",
"/naɪf/",
"/ˈʃaʊ ər/",
"/faɪər ɪkˈstɪŋ gwɪ ʃər/",
"/ˈkɛt l/",
"/kæn/",
"/ˈær oʊ/",
"/ˈrɛkˌtæŋ gəl/",
"/roʊp/",
"/ˈkæl kyəˌleɪ tər/",
"/ˈaɪ ərn/",
"/ˈru lər/",
"/əˈkɔr di ən/",
"/ˈklɒz ɪt/",
"/spɪər/",
"/ˈsæt lˌaɪt/",
"/ˈtrɛʒ ər/",
"/ˈpɛn səl ˈʃɑr pən/",
"/ˈtaɪpˌraɪ tər/",
"/ˈsɜr kəl/",
"/ˈpɪkˌæks/",
"/ˈhæm ək/",
"/ʰwɪp, wɪp/",
"/ˈæŋ kər/",
"/ˈlɛt ər/",
"/ˈkɜr tn/",
"/rɪˈfrɪdʒ əˌreɪ tər/",
"/dɔr, doʊr/",
"/ˈflæʃˌlaɪt/",
"/dɒl/",
"/ˈwɔ kɪŋ stɪk/",
"/gəˈrɪl ə/",
"/ræˈkun/",
"/ˈyu nɪˌkɔrn/",
"/ˈreɪnˌdɪər/",
"/gɪl/",
"/ˌhɪp əˈpɒt ə məs/",
"/græs, grɑs ˈhɒp ər/",
"/maʊs/",
"/fɪʃ/",
"/raɪˈnɒs ər əs/",
"/hɔrn/",
"/ˈtɜr tl/",
"/ˈdɛn tɪst/",
"/ˌɑr kiˈɒl ə dʒɪst/",
"/ˈdʒʌg lər/",
"/məˈkæn ɪk/",
"/ˈweɪ tər/",
"/ˈwɪn tər/",
"/tɔrˈneɪ doʊ/",
"/bʊʃ/",
"/ˈwɔ tərˌfɔl, ˈwɒt ər-/",
"/ˈplæn ɪt/",
"/deɪ/",
"/ˈæv əˌlæntʃ, -ˌlɑntʃ/",
"/sid/",
"/ˈsi zən/",
"/reɪn/",
"/boʊn/",
"/hɪp/",
"/hænd/",
"/nɜrv/",
"/maʊθ/",
"/pɑm/",
"/pil/",
"/ˈɔr ɪndʒ, ˈɒr-/",
"/ʰwit, wit/",
"/təˈmeɪ toʊ, -ˈmɑ-/",
"/skul/",
"/ˈdʒɛt i/",
"/ʃɒp/",
"/ˈæntˌhɪl/",
"/ˈʰwilˌbær oʊ, ˈwil-/",
"/ˈlaɪt nɪŋ/",
"/brʌʃ/",
"/ˈslɪŋˌʃɒt/",
"/ˈkɪtʃ ən/",
"/ˈkæn di/",
"/mʌŋk/",
"/sɔlt ˈʃeɪ kər/",
"/boʊl/",
"/ˈmaɪ krəˌfoʊn/",
"/breɪk/",
"/ˈbeɪ kə ri, ˈbeɪk ri/",
"/ˈtuθˌpeɪst/",
"/ˈswɛt ər/",
"/wʊlf/",
"/skɑrf/",
"/swɪm/",
"/ˈlɪm əˌzin, ˌlɪm əˈzin/",
"/taʊn/",
"/ˈsæl əd/",
"/ˈpæn tiz/",
"/ˈsænd wɪtʃ, ˈsæn-/",
"/ˈreɪnˌkoʊt/",
"/ˈmʌm i/",
"/ˈwɒtʃˌmeɪ kər/",
"/tæŋk/",
"/ˈlɛt ɪs/",
"/ˈlɪpˌstɪk/",
"/ˈɛgˌplænt, -ˌplɑnt/",
"/ˈæk tər/",
"/ˈʌn yən/",
"/ˈspɪn ɪtʃ/",
"/fud/",
"/waɪn/",
"/ˈdʒɪn dʒər/",
"/mɪlk/",
"/dʒəˈræf/",
"/pɪg/",
"/fəˈtɒg rə fər/",
"/ˈpiˌnʌt, -nət/",
"/ˈpaɪˌnæp əl/",
"/ˈsʌnˌflaʊ ər/",
"/neɪl/",
"/tɔrtʃ/",
"/faɪər trʌk/",
"/ˈɒl ɪv/",
"/ˈwɪn doʊ/",
"/ˌɑr məˈdɪl oʊ/",
"/əˈspær ə gəs/",
"/soʊl/",
"/ˈsɛlˌfoʊn/",
"/bʌg/",
"/ˈdʒɜr nl ɪst/",
"/ˈstroʊ lər/",
"/ˈsɛl ə ri, ˈsɛl ri/",
"/ˈbiˌki pər/",
"/hɛər klɪp/",
"/ˈplæs tər, ˈplɑ stər/",
"/ˈpeɪ pər klɪp/",
"/ˈi zəl/",
"/daɪ/",
"/ˈpɪr ə mɪd/",
"/ˈɑr tɪˌtʃoʊk/",
"/bəˈnæn ə/",
"/ˈpæl ɪt/",
"/kɪs/",
"/kwin/",
"/gɒlf, gɔlf klʌb/",
"/keɪk/",
"/ˈmaɪ krəˌskoʊp/",
"/ˈmæm əθ/",
"/ˈroʊ lɪŋ pɪn/",
"/dɛθ/",
"/pɔ/",
"/ˈtaɪ gər/",
"/ˈtʃɛk ər/",
"/ˈkæs əl, ˈkɑ səl/",
"/ˈaɪ rɪs/",
"/frɛntʃ fraɪz/",
"/dɪər/",
"/ˈpæn tiˌhoʊz/",
"/ˈreɪ zɪn/",
"/ˈɪg lu/",
"/rut, rʊt/",
"/wɒtʃ/",
"/ˈdɒk tər/",
"/gɪˈtɑr/",
"/ˈstɒk ɪŋ/",
"/bitʃ/",
"/ˈtræf ɪk laɪt/",
"/dɪˈtɛk tɪv/",
"/ɪnˈtɛs tɪn/",
"/hʊk/",
"/ˈzi brə/",
"/ˈfaʊn tn/",
"/bænd/",
"/ˈɑr mi/",
"/ˈkʊk i/",
"/lɔn ˈmoʊ ər/",
"/tʃɛs/",
"/ˈbeɪsˌbɔl bæt/",
"/ˌkær əˈsɛl, ˈkær əˌsɛl/",
"/gʌl/",
"/ˈsʌbˌweɪ/",
"/kɑrt/",
"/ˈɒk tə pəs/",
"/θif/",
"/ˈblækˌbɛr i, -bə ri/",
"/læmp/",
"/tuθ/",
"/dɔg, dɒg/",
"/goʊst/",
"/plʌm/",
"/mun/",
"/sæk/",
"/bɛlt/",
"/ˈpɪl oʊ/",
"/heɪl/",
"/ˈhæn dlˌbɑr/",
"/pi/",
"/wɛld/",
"/kwaɪər/",
"/ˈhɛdˌfoʊn/",
"/ˈfɑr mə si/",
"/ˈreɪ zər/",
"/gɜrl/",
"/waɪld bɔr, boʊr/",
"/kɜrb/",
"/ˈleɪd l/",
"/ˈbaɪn dər/",
"/bʌŋk bɛd/",
"/ˈhɛərˌdrɛs ər/",
"/ˈsɜr kəs/",
"/fɒks/",
"/baʊ/",
"/fɜrst eɪd/",
"/rid/",
"/ˈæl fəˌbɛt, -bɪt/",
"/ˈkʌm pəs/",
"/ˈpɛŋ gwɪn, ˈpɛn-/",
"/ˌtʃɪm pænˈzi/",
"/əˈstrɒn ə mər/",
"/kʌp/",
"/ˈbʌt ər/",
"/ˈwɪz ərd/",
"/vɛst/",
"/skʌl/",
"/sneɪk/",
"/ˈmʌs tæʃ, məˈstæʃ/",
"/prəˈpɛl ər/",
"/kɔrn/",
"/lɪd/",
"/ˈkreɪd l/",
"/ˈɪərˌmʌf/",
"/ˈbʌt n/",
"/ˈbaɪ sɪ kəl/",
"/piˈæn oʊ, ˈpyæn oʊ/",
"/keɪp/",
"/ˈkaʊˌbɔɪ/",
"/flut/",
"/ˈstritˌkɑr/",
"/ˈkɔ ləˌflaʊ ər/",
"/ˈlɔn dri, ˈlɑn-/",
"/bæk/",
"/ˈtræf ɪk dʒæm/",
"/ˈfɛər i/",
"/ˈskɛl ɪ tn/",
"/ˈsoʊl dʒər/",
"/ˈfaɪərˌwɜrk/",
"/ˈpɪtʃˌfɔrk/",
"/skwɛər/",
"/ˈmʌz əl/",
"/spul/",
"/swɪm fɪn/",
"/ˈru stər/",
"/ˌvaɪ əˈlɪn/",
"/lif/",
"/tɔɪ/",
"/ˈæp əl/",
"/ˈskɛərˌkroʊ/",
"/ˈlʌm bərˌdʒæk/",
"/tʃɛər/",
"/gɪft/",
"/ˈkæn ən/",
"/naɪt/",
"/ɪŋk/",
"/ˈtʃɪkˌpi/",
"/bɒks/",
"/ˈkrɔsˌwɜrd ˈpʌz əl/",
"/ˈstɑrˌfɪʃ/",
"/ˈɛl boʊ/",
"/stɪk/",
"/ˈbʊtʃ ər/",
"/skeɪl/",
"/ˈhɔrsˌʃu, ˈhɔrʃ-/",
"/ˈwɒʃ ɪŋ  məˈʃin/",
"/pəˈteɪ toʊ, -tə/",
"/kɔɪn/",
"/pæθ, pɑθ/",
"/ˈhɛərˌbrʌʃ/",
"/ˈɔɪnt mənt/",
"/ˈpyu pəl/",
"/ˈskɔr pi ən/",
"/ˈaɪˌlæʃ/",
"/piˈæn ɪst, ˈpyæn-, ˈpi ə nɪst/",
"/ˈsʌnˌraɪz/",
"/hɛd/",
"/ˈræd ɪʃ/",
"/ˈsoʊ ɪŋ məˈʃin/",
"/græs, grɑs/",
"/ˈɛgˌʃɛl/",
"/ˈbrɒk ə li, ˈbrɒk li/",
"/weɪv/",
"/fild/",
"/ni/",
"/pɒnd/",
"/ˈfaʊn tn pɛn/",
"/kəˈnu/",
"/bɪər/",
"/nɛst/",
"/ˈlɛt ər/",
"/ˈbɜr oʊ, ˈbʌr oʊ/",
"/ˈvʌl tʃər/",
"/ˈsni kər/",
"/glu/",
"/ˈsɜr dʒən/",
"/ˈskeɪ tər/",
"/ˈdaɪ nəˌsɔr/",
"/ˈfɪŋ gərˌprɪnt/",
"/ˈkrɒk əˌdaɪl/",
"/ˈbɒk sər/",
"/ˈmʌs əl/",
"/smoʊk/",
"/ˈʃɒp ɪŋ kɑr/",
"/ˈpoʊ niˌteɪl/",
"/bræntʃ, brɑntʃ/",
"/ˈrɒk ɪt/",
"/ˌkɒn stəˈleɪ ʃən/",
"/yɑrn/",
"/rɛntʃ/",
"/fɑrm/",
"/bʌs stɒp/",
"/ˈflɔr ɪst, ˈfloʊr-, ˈflɒr-/",
"/tʃeɪn/",
"/ˈprɪz ə nər, ˈprɪz nər/",
"/spʌndʒ/",
"/ˈdræg ənˌflaɪ/",
"/mæp/",
"/ˈmeɪlˌbɒks/",
"/sil/",
"/ˈlaɪ ən/",
"/ˈtraɪˌæŋ gəl/",
"/ˈfæk tə ri, -tri/",
"/ˈfaɪərˌfaɪ tɛr/",
"/pæn/",
"/klɒk/",
"/ˈæm byə ləns/",
"/ˈweɪ trɪs/",
"/ʃɛlf/",
"/ˈdʒu əl/",
"/tʃɪn/",
"/flɔr, floʊr/",
"/ˈpæs əˌfaɪ ər/",
"/ˈkɒm ɪt/",
"/ˈfɪʃ ər mən/",
"/pul/",
"/meɪz/",
"/kæˈʃɪər/",
"/ˈbær əl/",
"/raɪs/",
"/mæsk, mɑsk/",
"/ˈsændˌbɒks/",
"/ˈɛl ə fənt/",
"/dʌk/",
"/trʌk/",
"/rɒk/",
"/ˈhæŋ ər/",
"/ˈmæn tɪs/",
"/ˈʃʊg ər/",
"/hɑrt/",
"/roʊd/",
"/dun, dyun/",
"/goʊt/",
"/ˈkʌpˌkeɪk/",
"/ˈraɪ tər/",
"/ˈtulˌbɒks/",
"/ˈgɒg əl/",
"/ˈtaʊ əl, taʊl/",
"/gəˈrɑʒ, -ˈrɑdʒ/",
"/ˈtʃɔ kə lɪt/",
"/ʃrɪmp/",
"/ˈneɪ vəl/",
"/hʊf, huf/",
"/θroʊn/",
"/ˈskaɪˌskreɪ pər/",
"/brʊk/",
"/ˈsæn dl/",
"/ˈbɒt l/",
"/ˈɒt ər/",
"/noʊz/",
"/stɑr/",
"/toʊ/",
"/nɔrθ/",
"/frɒg, frɔg/",
"/ˈfɔ sɪt/",
"/ˈsɒk ər goʊl/",
"/ruf, rʊf/",
"/doʊm/",
"/ˈtaʊ ər/",
"/sænd/",
"/peɪnt/",
"/ˈfaɪərˌpleɪs/",
"/spun/",
"/keɪdʒ/",
"/stɛər/",
"/ruf, rʊf taɪl/",
"/ˈʃʌv əl/",
"/teɪp/",
"/kɪŋ/",
"/ˈdaɪ pər, ˈdaɪ ə pər/",
"/stæmp/",
"/ˈtreɪ lər/",
"/teɪl/",
"/ˈdræg ən/",
"/ˈʌn dərˌʃɜrt/",
"/ˈseɪ bər/",
"/ˈsku bə ˈdaɪ vər/",
"/ˈbreɪs lɪt/",
"/ˈmæn ɪ kɪn/",
"/slɛd/",
"/gʌn/",
"/sɔ/",
"/ˈkɔ fi, ˈkɒf i/",
"/klaʊn/",
"/hɛər ˈdraɪ ər/",
"/drʌg/",
"/ˈflaʊ ər/",
"/ˈsʌnˌsɛt/",
"/kɑr/",
"/kʊk/",
"/ˈlæd ər/",
"/gæs ˈsteɪ ʃən/",
"/ˈsteɪ di əm/",
"/bid/",
"/fɛns/",
"/ˈgrænˌdɔ tər/",
"/ˈgrænˌsʌn, ˈgrænd-/",
"/ˈtæd poʊl/",
"/ˈbiˌhaɪv/",
"/ˈkiˌbɔrd, -ˌboʊrd/",
"/wɜrld/",
"/ˈteɪ bəl/",
"/ˈgɒb lɪt/",
"/geɪm/",
"/brɛst/",
"/tʃiz/",
"/ˈsɜrfˌbɔrd, -ˌboʊrd/",
"/ʰwil, wil/",
"/aɪ ˈdɒk tər/",
"/ˈkæn dl/",
"/sɔrd, soʊrd/",
"/brɑ/",
"/ˈfɔr ɪst, ˈfɒr-/",
"/ˈdɛz ərt/",
"/ˈkɛm ɪst/",
"/ˈkloʊ vər/",
"/swɪtʃ/",
"/ˈbʊl ɪt/",
"/ˈkɪt n/",
"/ˈswɪv əl tʃɛər/",
"/ˈkɒl ər/",
"/ˈæk rəˌbæt/",
"/hɑrp/",
"/ˈtraɪ pɒd/",
"/ʃɑrk/",
"/ˈkæl ən dər/",
"/ræft, rɑft/",
"/ˈreɪ diˌeɪ tər/",
"/dʒɑr/",
"/bæg/",
"/ˈbit l/",
"/dɛsk/",
"/ˈʃuˈmeɪ kər/",
"/goʊld/",
"/ˈbɑrˌbɛl/",
"/ˈnoʊtˌbʊk/",
"/ˈkæm əl/",
"/ˈbʌt ərˌflaɪ/",
"/bɛd/",
"/ˈpæs pɔrt, -poʊrt, ˈpɑs-/",
"/flaɪt/",
"/ˈtæk si/",
"/hoʊˈtɛl/",
"/ˌrɛz ərˈveɪ ʃən/",
"/ˈnuzˌpeɪ pər/",
"/ˈrɛs tər ənt/",
"/ˈbæθˌrum, -ˌrʊm, ˈbɑθ-/",
"/ˈmɛn yu, ˈmeɪ nyu/",
"/mit/",
"/tʃɛk/",
"/tʃaɪld/",
"/ˈfæm ə li, ˈfæm li/",
"/ˈmʌð ər/",
"/ˈfɑ ðər/",
"/ˈhʌz bənd/",
"/waɪf/",
"/ˈbrʌð ər/",
"/dæd/",
"/mɒm/",
"/sʌn/",
"/ˈdɔ tər/",
"/ʃu/",
"/pænt/",
"/klæs, klɑs/",
"/pɛn/",
"/prəˈfɛs ər/",
"/aɪˈdi ə, aɪˈdiə/",
"/wɜrd/",
"/ˈwʊm ən/",
"/hɔrs/",
"/ˈɛm bə si/",
"/kæt/",
"/zu/",
"/wɛst/",
"/lɪp/",
"/skɪn/",
"/tʌŋ/",
"/pəˈlis/",
"/blʌd/",
"/ɪˈmɜr dʒən si/",
"/drɛs/",
"/ˈɪnˈsaɪd/",
"/bɔs, bɒs/",
"/ˈɔ fə sər, ˈɒf ə-/",
"/dɪˈrɛk tər, daɪ-/",
"/ˈsɛk rɪˌtɛr i/",
"/sɔs/",
"/ˈhʌn i/",
"/ˈtu nə, ˈtyu-/",
"/lʌntʃ/",
"/ˈdɪn ər/",
"/bif/",
"/dʒʌdʒ/",
"/ˈɔ θər/",
"/ˈlɔ yər, ˈlɔɪ ər/",
"/ˈwɜr kər/",
"/prəˈfɛʃ ə nl/",
"/ˈæn ə məl/",
"/prəˈfɛʃ ən/",
"/taɪm/",
"/deɪt/",
"/ˈsɛn tʃə ri/",
"/bɜrθ/",
"/ˈpɪər i əd/",
"/ˈsʌm ər/",
"/ˈiv nɪŋ/",
"/ˈsɛk ənd/",
"/steɪdʒ/",
"/ˈpɑ stə/",
"/ˈtʃɪk ən/",
"/pleɪt/",
"/ˈæn sər, ˈɑn-/",
"/sup/",
"/ˈbrɛk fəst/",
"/pɔrk, poʊrk/",
"/ɔɪl/",
"/ˈkʌl ər/",
"/frɛnd/",
"/ˈʌŋ kəl/",
"/haʊs/",
"/ˈpɑr ti/",
"/bɜrd/",
"/neɪm/",
"/ˈwɪm ɪn/",
"/dʒɒb/",
"/ˈstud nt, ˈstyud-/",
"/ˈpɛər ənt, ˈpær-/",
"/ˈsɪs tər/",
"/ˈreɪ diˌoʊ/",
"/wɔl/",
"/ˈkæb ə nɪt/",
"/ˈtɛl əˌfoʊn/",
"/skrin/",
"/ˈkʌn tri/",
"/ˈsɛn tər/",
"/ˈbɔr dər/",
"/ˈvæl i/",
"/rut, raʊt/",
"/ˈmɒd l/",
"/<ˌæf tərˈnun, ˌɑf-/",
"/ˈdɛk eɪd/",
"/hoʊm/",
"/ˈɔ fɪs, ˈɒf ɪs/",
"/ˈæv ər ɪdʒ, ˈæv rɪdʒ/",
"/hæf, hɑf/",
"/mil/",
"/ˌyu nəˈvɜr sɪ ti/",
"/tɛst/",
"/ˈdɒk yə mənt/",
"/kɔrs, koʊrs/",
"/ˌprɛz ənˈteɪ ʃən/",
"/ˈɪn stɪˌtut, -ˌtyut/",
"/pɛr/",
"/ˈtiˈvi/",
"/ˈtɛl əˌvɪʒ ən/",
"/aʊər, ˈaʊ ər/",
"/ænt, ɑnt/",
"/ˈɪl nɪs/",
"/saɪt/",
"/ˈæk sɪ dənt/",
"/məˈtɪər i əl/",
"/feɪθ/",
"/ˈɛg zɪt, ˈɛk sɪt/",
"/ˈmɜr dər/",
"/ʃeɪp/",
"/ˈdeɪn dʒər/",
"/ˈɪn tər ɪst, -trɪst/",
"/strɛŋkθ, strɛŋθ, strɛnθ/",
"/trəˈdɪʃ ən/",
"/rɪˈleɪ ʃən/",
"/ˈdɪs təns/",
"/dɛpθ/",
"/tæsk, tɑsk/",
"/ˈvɒl yum, -yəm/",
"/ˈsaɪ əns/",
"/dʒiˈɒg rə fi/",
"/ˈɑr tɪ kəl/",
"/weɪt/",
"/ˌpʌb lɪˈkeɪ ʃən/",
"/laɪn/",
"/tɛkˈnik/",
"/dɒt/",
"/ˈkɒn sɛpt/",
"/wɛlθ/",
"/spitʃ/",
"/straɪk/",
"/dɛt/",
"/ɪˈkɒn ə mi/",
"/sɪˈkyʊər ɪ ti/",
"/ˈprɛz ɪ dənt/",
"/ˈɪn tərˌnɛt/",
"/ˈnɛtˌwɜrk/",
"/ˈtʃæn l/",
"/ˈlæŋ gwɪdʒ/",
"/tɛkst/",
"/kəˌmyu nɪˈkeɪ ʃən/",
"/fɪlm/",
"/ˈmyu zɪk/",
"/ˈpoʊ ɪ tri/",
"/ˈfæʃ ən/",
"/saʊnd/",
"/kəˈlɛk ʃən/",
"/ˈpɪk tʃər/",
"/ˈkɒn tɛst/",
"/dɪˈzaɪn/",
"/ˈɪʃ u/",
"/ˈmæt ər/",
"/ˈyun yən/",
"/səkˈsɛs/",
"/wɪʃ/",
"/rɪˈspɒns/",
"/əˈgri mənt/",
"/ɪˈlɛk ʃən/",
"/ˈkɒn flɪkt/",
"/ædˈvaɪs/",
"/bleɪm/",
"/θrɛt/",
"/ˈkɒŋ grɪs/",
"/ˈsɛn ə tər/",
"/dɪˈsɪʒ ən/",
"/ˈwɛp ən/",
"/voʊt/",
"/ˈneɪ vi/",
"/ˈgʌv ər nər, ‐ə nər/",
"/lɛg/",
"/hɛlθ/",
"/ˈbɒd i/",
"/ˈtrit mənt/",
"/fit/",
"/tiθ/",
"/ˈvɪʒ ən/",
"/kənˈdɪʃ ən/",
"/drim/",
"/hɛlp/",
"/ˈvaɪ rəs/",
"/ˌɪn fərˈmeɪ ʃən/",
"/ˈkɒm ɛnt/",
"/ˈstɔr i, ˈstoʊr i/",
"/ˈmɛs ɪdʒ/",
"/ˈæk sɛs/",
"/ˈɪn strə mənt/",
"/ˈfɪg yər/",
"/dæns, dɑns/",
"/staɪl/",
"/ɑrt/",
"/ˈkɒn sɜrt, -sərt/",
"/mætʃ/",
"/stoʊn/",
"/ˈyu nəˌvɜrs/",
"/ˌkɒm pɪˈtɪʃ ən/",
"/ˈɛf ərt/",
"/eɪm/",
"/ˌɪn trəˈdʌk ʃən/",
"/ækt/",
"/ˈvæl yu/",
"/ˈsɪs təm/",
"/ˈtʃæp tər/",
"/ˌæp lɪˈkeɪ ʃən/",
"/ˈhɪs tə ri, ˈhɪs tri/",
"/ˈproʊ græm, -grəm/",
"/gaɪd/",
"/ˈpi pəl/",
"/ˈsɪt ə zən, -sən/",
"/yuθ/",
"/ˈkʌl tʃər/",
"/ˈvɪk tɪm/",
"/faʊnˈdeɪ ʃən/",
"/kəˈmɪt i/",
"/ˈɛn ə mi/",
"/ˌpɒp yəˈleɪ ʃən/",
"/frʌnt/",
"/ˈsɪn ə mə/",
"/ˌmæg əˈzin, ˈmæg əˌzin/",
"/θɪŋ/",
"/ˈmær ɪdʒ/",
"/ˈneɪ tʃər/",
"/ˈæk trɪs/",
"/ˈmu vi/",
"/ˈθi ə tər, ˈθiə-/",
"/ˈlɛk tʃər/",
"/əbˈdʒɛk tɪv/",
"/ˈpræk tɪs/",
"/ˌɛdʒ ʊˈkeɪ ʃən/",
"/peɪdʒ/",
"/ˈsɛk ʃən/",
"/ˈstʌd i/",
"/ˈæv əˌnyu, -ˌnu/",
"/kəˈmyu nɪ ti/",
"/saɪt/",
"/zoʊn/",
"/ˈpaʊ dər/",
"/ˈvɪz ɪt/",
"/ˌtræns pərˈteɪ ʃən/",
"/saʊθ/",
"/ˈmoʊ tər/",
"/ˈnɒv əl/",
"/strɪŋ/",
"/speɪs/",
"/ˈsɪg nl/",
"/ˈkʌp əl/",
"/ˌɪn dəˈvɪdʒ u əl/",
"/ˈbeɪ bi/",
"/ˈpʌb lɪk/",
"/ˈvɪl ɪdʒ/",
"/ˈmɪr ər/",
"/ˈbæs kɪt, ˈbɑ skɪt/",
"/stæf, stɑf/",
"/tʃɑrdʒ/",
"/ˈɛv ɪ dəns/",
"/ˈæl kəˌhɔl, -ˌhɒl/",
"/ˈæθ lit/",
"/dʒɪm/",
"/koʊtʃ/",
"/pɔɪnt/",
"/ˈbæs kɪtˌbɔl, ˈbɑ skɪt-/",
"/ˈpleɪ ər/",
"/stɛp/",
"/spɔrt, spoʊrt/",
"/liv/",
"/ˈklaɪ mɪt/",
"/sɔɪl/",
"/ˈwɛð ər/",
"/ˈmɛm ə ri/",
"/ˈɛn trəns/",
"/ˈæt ɪˌtud, -ˌtyud/",
"/ˈɒn ər/",
"/mɪˈsteɪk/",
"/dʒɔɪ/",
"/ˈfeɪ vər/",
"/trɛnd/",
"/freɪz/",
"/sərˈpraɪz, sə-/",
"/fɔlt/",
"/ˌkɒn vərˈseɪ ʃən/",
"/dɪˈzaɪər/",
"/ˈkɒn sɪˌkwɛns/",
"/ˈplɛʒ ər/",
"/ɪgˈzɪs təns/",
"/rɪˌspɒn səˈbɪl ɪ ti/",
"/daʊt/",
"/ˈhyu mər/",
"/ˈpɜr mɪt/",
"/pəˈzɪʃ ən/",
"/ɪkˈspɪər i əns/",
"/ˈsɪm bəl/",
"/sin/",
"/ˈsɪg nə tʃər, -ˌtʃʊər/",
"/dɪˈrɛk ʃən, ˈdaɪ-/",
"/əˈtɛmpt/",
"/bɪˈheɪv yər/",
"/ˈkær ɪk tər/",
"/ˈdæm ɪdʒ/",
"/ˈɔr ɪ dʒɪn, ˈɒr-/",
"/riˈæl ɪ ti/",
"/ˈfeɪl yər/",
"/truθ/",
"/lɪv/",
"/loʊd/",
"/pərˈmɪʃ ən/",
"/ˌsɪtʃ uˈeɪ ʃən/",
"/ˈbɛn ə fɪt/",
"/ˈtaɪt l/",
"/əˈtɛn ʃən/",
"/rɪˈspɛkt/",
"/rɪˈlɪdʒ ən/",
"/əˈmaʊnt/",
"/ɔlˈtɜr nə tɪv, æl-/",
"/kaɪnd/",
"/ˈsʌb dʒɪkt/",
"/əˈwɔrd/",
"/ˈpɜr pəs/",
"/roʊl/",
"/vɔɪs/",
"/tʃɔɪs/",
"/ˈdɪf ɪˌkʌl ti, -kəl ti/",
"/ˌɛk spləˈneɪ ʃən/",
"/ˈri dʒən/",
"/graʊnd/",
"/yɑrd/",
"/ˈɒb dʒɪkt, -dʒɛkt/",
"/dɪˈpɑrt mənt/",
"/pis/",
"/ˈmɑr kɪt/",
"/ˈɑr tɪst/",
"/ˈsɪb lɪŋ/",
"/ˈkwɛs tʃən/",
"/əˈdrɛs, ˈæd rɛs/",
"/tʃeɪndʒ/",
"/rɪˈvyu/",
"/məˈdʒɔr ɪ ti, -ˈdʒɒr-/",
"/ˈɛn tri/",
"/ɪˈfɛkt/",
"/ˌɒp ərˈtu nɪ ti, -ˈtyu-/",
"/hoʊp/",
"/maɪnd/",
"/tɜrn/",
"/kənˈstrʌk ʃən/",
"/prəˈtɛk ʃən/",
"/prəˈdʌk ʃən/",
"/səˈlu ʃən/",
"/rɪˈzʌlt/",
"/rɪˈzʌlt/",
"/ˈɒp ʃən/",
"/ˈprɒb ləm/",
"/ækˈtɪv ɪ ti/",
"/ˈkɒn tɛnt/",
"/ɪˈkwɪp mənt/",
"/ˈkæt ɪˌgɔr i, -ˌgoʊr i/",
"/dɪˈskrɪp ʃən/",
"/ˈɪm ɪdʒ/",
"/kɔl/",
"/əˈkaʊnt/",
"/ˈproʊ faɪl/",
"/kənˈtroʊl/",
"/ˈmɛm bər/",
"/grup/",
"/keɪs/",
"/ˈɔr dər/",
"/ˈvɜr ʒən, -ʃən/",
"/vyu/",
"/pɑrt/",
"/ˈsɜr vɪs/",
"/sʌm/",
"/ˈnʌm bər/",
"/dɪˈpɑr tʃər/",
"/ˈdʒɜr ni/",
"/ˈtʊər ɪst/",
"/brɪdʒ/",
"/ædˈvɛn tʃər/",
"/ˈvi ɪ kəl/",
"/ˈmoʊ tərˌsaɪ kəl/",
"/tɛnt/",
"/flu/",
"/gaɪ/",
"/ˈlʌg ɪdʒ/",
"/ˈkɒt n/",
"/ˈeɪl yən, ˈeɪ li ən/",
"/ˈbʊkˌmɑrk/",
"/ˈspi kər/",
"/ˈpɪkˌpɒk ɪt/",
"/hʌt/",
"/wɪnd/",
"/ɛər/",
"/ˈlɪr ɪk/",
"/teɪst/",
"/ˈdɑr lɪŋ/",
"/kraʊd/",
"/soʊl/",
"/plæn/",
"/tɪər/",
"/peɪn/",
"/ruˈtin/",
"/ˈdrɔ ɪŋ/",
"/preɪ/",
"/dɪˈdʒɛs tʃən, daɪ-/",
"/glæns, glɑns/",
"/kənˈsɜrn/",
"/ˈoʊ ʃən/",
"/əˈmeɪz mənt/",
"/blɪŋk/",
"/ˈpɔr trɪt, -treɪt, ˈpoʊr-/",
"/glim/",
"/fækt/",
"/ɪmˈpɔr tns/",
"/ˈtɛl əˌskoʊp/",
"/rɪˈpɔrt, -ˈpoʊrt/",
"/dʌv/",
"/pruf/",
"/ˈʃoʊl dər/",
"/fɔrˈbɛər əns/",
"/ɪnˈdɪf ər əns/",
"/grif/",
"/ˈbɒd iˌgɑrd/",
"/rɪˈlis/",
"/əˈpɪər əns/",
"/dɪˈvɛl əp mənt/",
"/ˈfʌŋk ʃə nl/",
"/ˈhæŋ ər/",
"/ˈkɑr nə vəl/",
"/ˈfi tʃər/",
"/ˈɔ fər, ˈɒf ər/",
"/ˈpeɪ mənt/",
"/ˈsɜr vər/",
"/ˈpɑrt nər/",
"/ˈkreɪd l/",
"/sliv/",
"/ˈkrɒk ə ri/",
"/ˈmaɪ kroʊˌweɪv/",
"/ˈtoʊ stər/ ",
"/hɒb/"];